import type { BankQuestion } from "./bank";

// Kho 100 câu concept Ngược Dòng: đời thường, công việc, cảm xúc hằng ngày.
export const BANK_NGUOC_DONG: BankQuestion[] = [
  {
    id: "nd001",
    title: "Chuông báo thức",
    sit: "Chuông reo 6h30, ngoài trời còn tối, chăn thì ấm. Hôm nay cũng không có việc gì quá gấp.",
    opts: [
      { t: "Bật dậy luôn. Nằm ráng chỉ làm cả ngày uể oải.", s: "khoi_xuong" },
      { t: "Dậy đúng giờ như mọi ngày — kỷ luật là kỷ luật.", s: "kien_tao" },
      { t: "Nằm thêm 5 phút tính xem hôm nay việc gì đáng dậy sớm.", s: "dan_duong" },
      { t: "Với tay tắt chuông rồi ngủ tiếp, kệ mai tính.", s: "tam_guong" },
    ],
  },
  {
    id: "nd002",
    title: "Tin nhắn sếp lúc nửa đêm",
    sit: "11h đêm, sếp nhắn: “Mai họp sớm, em chuẩn bị giúp anh số liệu nhé.” Bạn đang chuẩn bị ngủ.",
    opts: [
      { t: "Mở máy làm luôn cho xong, mai khỏi cuống.", s: "kien_tao" },
      { t: "Nhắn lại: để mai em làm đầu giờ, giờ này số liệu dễ sai.", s: "dan_duong" },
      { t: "Thấy tin mà tim đập thình thịch, lo không ngủ được.", s: "tam_guong" },
      { t: "Gọi thẳng cho sếp hỏi cần gấp cỡ nào rồi quyết.", s: "khoi_xuong" },
    ],
  },
  {
    id: "nd003",
    title: "Kẹt xe giờ cao điểm",
    sit: "Bạn kẹt cứng giữa dòng xe, đồng hồ báo sắp trễ họp 10 phút. Xung quanh ai cũng bấm còi.",
    opts: [
      { t: "Quan sát rồi luồn ngay lối tắt mình biết.", s: "khoi_xuong" },
      { t: "Chấp nhận trễ, tranh thủ nghe lại nội dung họp.", s: "kien_tao" },
      { t: "Nhắn cả nhóm: họp trễ 15 phút, gửi trước tài liệu.", s: "dan_duong" },
      { t: "Bồn chồn, áy náy, cứ tưởng tượng mặt mọi người chờ mình.", s: "tam_guong" },
    ],
  },
  {
    id: "nd004",
    title: "Đồng nghiệp mượn tiền",
    sit: "Đồng nghiệp thân hỏi mượn 5 triệu “xoay vài hôm”. Bạn không dư dả nhưng cũng không túng.",
    opts: [
      { t: "Chuyển luôn. Bạn bè giúp được thì giúp.", s: "khoi_xuong" },
      { t: "Cho mượn một nửa — vừa giúp vừa giữ an toàn cho mình.", s: "kien_tao" },
      { t: "Hỏi rõ cần việc gì, rồi mới quyết có nên cho mượn không.", s: "dan_duong" },
      { t: "Không dám từ chối nên ừ đại, về nhà tiếc cả tối.", s: "tam_guong" },
    ],
  },
  {
    id: "nd005",
    title: "Cuộc họp vô nghĩa",
    sit: "Họp đã 1 tiếng mà chưa vào trọng tâm, ai cũng nhìn đồng hồ. Bạn là người nhỏ nhất phòng.",
    opts: [
      { t: "Lên tiếng: “Mình chốt 3 việc chính rồi tan họp nhé?”", s: "khoi_xuong" },
      { t: "Ngồi ghi chép đầy đủ, họp xong làm phần mình.", s: "kien_tao" },
      { t: "Im lặng quan sát xem ai đang lái cuộc họp đi đâu.", s: "dan_duong" },
      { t: "Thấy ai cũng chán nên mình cũng chán theo, chẳng muốn nói gì.", s: "tam_guong" },
    ],
  },
  {
    id: "nd006",
    title: "Việc gấp đổ lên đầu",
    sit: "4h chiều thứ Sáu, sếp giao thêm việc “sáng thứ Hai phải có”. Bạn đã có kế hoạch cuối tuần.",
    opts: [
      { t: "Hủy kèo, ở lại làm cho xong rồi về cho nhẹ đầu.", s: "kien_tao" },
      { t: "Hỏi sếp: việc này có dời được không, hay thật sự gấp?", s: "dan_duong" },
      { t: "Nhận lời cho yên chuyện, dù trong lòng ấm ức.", s: "tam_guong" },
      { t: "Nói thẳng: cuối tuần này em bận, thứ Hai em ưu tiên đầu tiên.", s: "khoi_xuong" },
    ],
  },
  {
    id: "nd007",
    title: "Món ăn thất bại",
    sit: "Bạn nấu món mới đãi cả nhà, nếm thử thấy… dở tệ. Còn 30 phút nữa là dọn cơm.",
    opts: [
      { t: "Đổ đi nấu món tủ cho chắc, không liều.", s: "khoi_xuong" },
      { t: "Chữa cháy: nêm nếm lại, thêm thắt đến khi ăn được.", s: "kien_tao" },
      { t: "Dừng lại xem sai ở bước nào để lần sau không tái phạm.", s: "dan_duong" },
      { t: "Buồn và tự trách, thấy mình vụng về quá.", s: "tam_guong" },
    ],
  },
  {
    id: "nd008",
    title: "Sale sập sàn",
    sit: "Món đồ bạn thích giảm 50% nhưng chỉ trong hôm nay. Tài khoản thì vừa đủ, không dư.",
    opts: [
      { t: "Chốt đơn ngay. Cơ hội không đến hai lần.", s: "khoi_xuong" },
      { t: "Bỏ qua — chưa thật sự cần thì rẻ cũng là đắt.", s: "kien_tao" },
      { t: "So giá 3 shop rồi mới quyết có mua không.", s: "dan_duong" },
      { t: "Thấy ai cũng khoe mua được nên cũng muốn mua theo.", s: "tam_guong" },
    ],
  },
  {
    id: "nd009",
    title: "Bạn rủ nhậu giữa tuần",
    sit: "Thứ Tư, hội bạn rủ nhậu “vui thôi”. Mai bạn có việc quan trọng lúc 8h sáng.",
    opts: [
      { t: "Đi! Vui là chính, mai tính sau.", s: "khoi_xuong" },
      { t: "Từ chối để mai tỉnh táo — việc quan trọng hơn.", s: "kien_tao" },
      { t: "Ghé một lát rồi về sớm, giữ cả hai.", s: "dan_duong" },
      { t: "Không nỡ từ chối nên đi, dù biết mai sẽ mệt.", s: "tam_guong" },
    ],
  },
  {
    id: "nd010",
    title: "Lời chê của mẹ",
    sit: "Mẹ gọi điện: “Bằng tuổi mày người ta nhà xe đủ cả.” Bạn nghe mà nghẹn họng.",
    opts: [
      { t: "Đáp luôn: “Con có đường của con, mẹ đừng so.”", s: "khoi_xuong" },
      { t: "Im lặng nghe, cúp máy rồi cày tiếp cho mẹ thấy.", s: "kien_tao" },
      { t: "Hỏi mẹ thật sự lo điều gì cho mình.", s: "dan_duong" },
      { t: "Buồn cả ngày, thấy mình đúng là thua kém người ta.", s: "tam_guong" },
    ],
  },
  {
    id: "nd011",
    title: "Deadline dí",
    sit: "Còn 2 tiếng nữa nộp bài mà bạn mới làm được nửa. Tay bắt đầu run.",
    opts: [
      { t: "Làm phần quan trọng nhất trước, phần râu ria bỏ.", s: "khoi_xuong" },
      { t: "Tắt điện thoại, cày một mạch không nghỉ.", s: "kien_tao" },
      { t: "Dừng 5 phút sắp xếp lại thứ tự ưu tiên rồi làm.", s: "dan_duong" },
      { t: "Càng gấp càng rối, cứ lo sếp sẽ nghĩ gì về mình.", s: "tam_guong" },
    ],
  },
  {
    id: "nd012",
    title: "Người yêu giận",
    sit: "Người yêu nhắn cụt lủn cả buổi, hỏi thì bảo “không có gì”. Bạn biết chắc là có gì.",
    opts: [
      { t: "Chạy sang gặp mặt nói cho ra lẽ ngay.", s: "khoi_xuong" },
      { t: "Nhắn dài xin lỗi và hứa bù đắp cuối tuần.", s: "kien_tao" },
      { t: "Để họ nguội đã, tối hỏi lại cho rõ.", s: "dan_duong" },
      { t: "Bồn chồn không làm được việc gì, cứ đoán già đoán non.", s: "tam_guong" },
    ],
  },
  {
    id: "nd013",
    title: "Tiền thưởng bất ngờ",
    sit: "Công ty thưởng nóng 10 triệu ngoài dự kiến. Cả phòng đang bàn nhau tiêu gì.",
    opts: [
      { t: "Tự thưởng ngay món mình thèm bấy lâu.", s: "khoi_xuong" },
      { t: "Bỏ hết vào tiết kiệm, không suy nghĩ.", s: "kien_tao" },
      { t: "Chia 3 phần: tiết kiệm, gia đình, bản thân.", s: "dan_duong" },
      { t: "Thấy mọi người mua sắm cũng ngứa tay muốn mua theo.", s: "tam_guong" },
    ],
  },
  {
    id: "nd014",
    title: "Ốm mà việc nhiều",
    sit: "Bạn sốt 38 độ nhưng hôm nay có 2 cuộc họp quan trọng. Đầu đau như búa bổ.",
    opts: [
      { t: "Uống thuốc rồi đi làm. Việc không chờ mình khỏi.", s: "kien_tao" },
      { t: "Xin nghỉ, nhắn rõ tiến độ để người khác cover.", s: "dan_duong" },
      { t: "Đi làm vì sợ mọi người nghĩ mình lười.", s: "tam_guong" },
      { t: "Hủy hết, tắt máy ngủ một giấc cho dứt điểm.", s: "khoi_xuong" },
    ],
  },
  {
    id: "nd015",
    title: "Drama công sở",
    sit: "Hai đồng nghiệp cãi nhau trong nhóm chat, một người tag bạn vào nhờ “phân xử”.",
    opts: [
      { t: "Nói thẳng quan điểm của mình, ai sai thì nhận.", s: "khoi_xuong" },
      { t: "Không xen vào, lo việc của mình cho xong.", s: "kien_tao" },
      { t: "Nhắn riêng từng người để hiểu chuyện gì xảy ra.", s: "dan_duong" },
      { t: "Khó xử, sợ bênh ai cũng mất lòng người kia.", s: "tam_guong" },
    ],
  },
  {
    id: "nd016",
    title: "Cuối tuần trống lịch",
    sit: "Lần đầu tiên sau 2 tháng, cuối tuần này bạn hoàn toàn rảnh. Không ai rủ, không việc gì gấp.",
    opts: [
      { t: "Xách xe đi đâu đó ngay, ở nhà là phí.", s: "khoi_xuong" },
      { t: "Dọn nhà, giặt giũ, xử lý đống việc tồn.", s: "kien_tao" },
      { t: "Ngồi lên kế hoạch cho tuần mới thật chỉn chu.", s: "dan_duong" },
      { t: "Nằm lướt điện thoại cả ngày, tối thấy trống rỗng.", s: "tam_guong" },
    ],
  },
  {
    id: "nd017",
    title: "Mất ví",
    sit: "Bạn phát hiện mất ví: giấy tờ, thẻ, ít tiền mặt. Lần cuối thấy nó là ở quán cafe sáng nay.",
    opts: [
      { t: "Quay lại quán ngay, vừa đi vừa gọi điện hỏi.", s: "khoi_xuong" },
      { t: "Bình tĩnh khóa thẻ, liệt kê giấy tờ cần làm lại.", s: "kien_tao" },
      { t: "Ngồi nhớ lại từng chặng đường để khoanh vùng.", s: "dan_duong" },
      { t: "Hoảng và tự trách mình hậu đậu, chân tay luống cuống.", s: "tam_guong" },
    ],
  },
  {
    id: "nd018",
    title: "Lời mời đám cưới xa",
    sit: "Bạn cũ mời cưới ở tỉnh xa, đi lại mất cả ngày cuối tuần. Quan hệ hai người cũng bình thường.",
    opts: [
      { t: "Đi luôn cho vui, coi như đổi gió.", s: "khoi_xuong" },
      { t: "Chuyển khoản mừng, nhắn lời chúc tử tế.", s: "kien_tao" },
      { t: "Xem lịch rồi quyết — đáng đi thì đi.", s: "dan_duong" },
      { t: "Ngại không đi thì mất lòng nên ráng đi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd019",
    title: "Bị sếp phê bình",
    sit: "Sếp chê thẳng trong họp: “Phần này làm ẩu quá.” Cả phòng im lặng nhìn bạn.",
    opts: [
      { t: "Nhận lỗi ngay và hứa sửa trong hôm nay.", s: "khoi_xuong" },
      { t: "Im lặng ghi nhận, về sửa lại gấp đôi chất lượng.", s: "kien_tao" },
      { t: "Hỏi lại sếp cụ thể ẩu ở đâu để sửa đúng.", s: "dan_duong" },
      { t: "Mặt nóng bừng, cả buổi họp không nghe được gì nữa.", s: "tam_guong" },
    ],
  },
  {
    id: "nd020",
    title: "Ý tưởng lúc nửa đêm",
    sit: "1h sáng, bạn nảy ra ý tưởng kinh doanh cực hay. Tim đập nhanh, không ngủ được.",
    opts: [
      { t: "Bật dậy ghi lại và nhắn ngay cho đứa bạn hợp cạ.", s: "khoi_xuong" },
      { t: "Ghi vào sổ rồi ngủ — mai tỉnh táo tính tiếp.", s: "kien_tao" },
      { t: "Nằm phân tích xem ý tưởng này ăn ở điểm nào.", s: "dan_duong" },
      { t: "Phấn khích một lúc rồi nghĩ “chắc không làm nổi đâu”.", s: "tam_guong" },
    ],
  },
  {
    id: "nd021",
    title: "Hàng xóm hát karaoke",
    sit: "10h đêm, nhà bên hát karaoke ầm ĩ. Mai bạn phải dậy sớm.",
    opts: [
      { t: "Sang gõ cửa nói thẳng luôn.", s: "khoi_xuong" },
      { t: "Đeo tai nghe, bật nhạc của mình át đi.", s: "kien_tao" },
      { t: "Chờ thêm 15 phút, không dứt mới sang nói.", s: "dan_duong" },
      { t: "Bực mà không dám nói, trằn trọc cả đêm.", s: "tam_guong" },
    ],
  },
  {
    id: "nd022",
    title: "Quên sinh nhật bạn thân",
    sit: "Tối mới nhớ ra hôm nay là sinh nhật bạn thân mà bạn chưa chúc gì. Điện thoại đầy ảnh tiệc của họ.",
    opts: [
      { t: "Gọi ngay, xin lỗi và hẹn bù một chầu.", s: "khoi_xuong" },
      { t: "Đặt quà giao gấp trong đêm kèm thiệp tay.", s: "kien_tao" },
      { t: "Nhắn tin chân thành, để mai gặp nói tiếp.", s: "dan_duong" },
      { t: "Áy náy đến mức không dám nhắn luôn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd023",
    title: "Thang máy kẹt",
    sit: "Thang máy chung cư kẹt giữa tầng, trong có 4 người lạ. Đèn chớp tắt.",
    opts: [
      { t: "Bấm chuông khẩn cấp, trấn an mọi người thật to rõ.", s: "khoi_xuong" },
      { t: "Bình tĩnh đứng chờ, tranh thủ trả lời tin nhắn.", s: "kien_tao" },
      { t: "Quan sát bảng điều khiển, thử các nút theo trình tự.", s: "dan_duong" },
      { t: "Tim đập loạn, càng thấy người khác hoảng càng hoảng theo.", s: "tam_guong" },
    ],
  },
  {
    id: "nd024",
    title: "Đồng nghiệp mới giỏi hơn",
    sit: "Người mới vào 1 tháng mà làm nhanh gấp đôi bạn. Sếp khen họ suốt.",
    opts: [
      { t: "Hỏi thẳng bí quyết của họ để học.", s: "khoi_xuong" },
      { t: "Cày thêm giờ để không bị bỏ lại.", s: "kien_tao" },
      { t: "Quan sát cách họ làm việc để rút kinh nghiệm.", s: "dan_duong" },
      { t: "Tự ti, thấy mình sắp bị thay thế.", s: "tam_guong" },
    ],
  },
  {
    id: "nd025",
    title: "Mưa lớn không áo mưa",
    sit: "Tan làm trời đổ mưa to, bạn không mang áo mưa. Nhà cách 5 cây số.",
    opts: [
      { t: "Đội mưa về luôn, ướt thì thay đồ.", s: "khoi_xuong" },
      { t: "Mua áo mưa ở tạp hóa gần nhất rồi về.", s: "kien_tao" },
      { t: "Ngồi chờ 20 phút xem mưa có ngớt không.", s: "dan_duong" },
      { t: "Đứng nhìn mọi người về mà tủi thân.", s: "tam_guong" },
    ],
  },
  {
    id: "nd026",
    title: "Bị hiểu lầm",
    sit: "Câu đùa của bạn trong nhóm chat bị một người hiểu thành móc mỉa. Họ nhắn lại khá căng.",
    opts: [
      { t: "Giải thích ngay trong nhóm cho rõ ràng.", s: "khoi_xuong" },
      { t: "Nhắn riêng xin lỗi, dù mình không cố ý.", s: "kien_tao" },
      { t: "Đọc lại tin nhắn xem mình sai ở đâu trước đã.", s: "dan_duong" },
      { t: "Buồn và im lặng, sợ nói gì cũng sai thêm.", s: "tam_guong" },
    ],
  },
  {
    id: "nd027",
    title: "Tăng ca hay về đúng giờ",
    sit: "Việc hôm nay xong 90%, 10% còn lại để mai cũng được. Đồng hồ điểm 5h30.",
    opts: [
      { t: "Về! Mai làm tiếp, đầu óc tỉnh táo hơn.", s: "khoi_xuong" },
      { t: "Ở lại làm nốt cho trọn vẹn rồi về.", s: "kien_tao" },
      { t: "Xem 10% đó có ai chờ không, không thì về.", s: "dan_duong" },
      { t: "Thấy cả phòng chưa ai về nên cũng ngồi lại.", s: "tam_guong" },
    ],
  },
  {
    id: "nd028",
    title: "Người lạ xin giúp đỡ",
    sit: "Cụ già bán vé số mời bạn mua, bạn vừa hết tiền lẻ. Cụ nhìn bạn đầy hy vọng.",
    opts: [
      { t: "Chuyển khoản mua giúp 2 tờ luôn.", s: "khoi_xuong" },
      { t: "Xin lỗi cụ rồi đi — giúp trong khả năng thôi.", s: "kien_tao" },
      { t: "Dừng lại hỏi han xem cụ cần gì hơn.", s: "dan_duong" },
      { t: "Thấy thương mà ngại, lảng đi rồi day dứt mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd029",
    title: "Điện thoại hết pin",
    sit: "Bạn đang chờ cuộc gọi quan trọng thì điện thoại sập nguồn. Không mang sạc.",
    opts: [
      { t: "Chạy ngay vào quán gần nhất mượn sạc.", s: "khoi_xuong" },
      { t: "Mượn điện thoại người quen gọi báo lại.", s: "kien_tao" },
      { t: "Tìm chỗ ngồi chờ, tranh thủ sắp xếp suy nghĩ.", s: "dan_duong" },
      { t: "Lo lắng bồn chồn, sợ lỡ mất cơ hội.", s: "tam_guong" },
    ],
  },
  {
    id: "nd030",
    title: "Khen thưởng trước đám đông",
    sit: "Sếp gọi tên bạn lên nhận thưởng nhân viên xuất sắc. Cả trăm người vỗ tay.",
    opts: [
      { t: "Bước lên tự tin, phát biểu cảm ơn ngắn gọn.", s: "khoi_xuong" },
      { t: "Nhận thưởng rồi về chỗ, để kết quả tự nói.", s: "kien_tao" },
      { t: "Cảm ơn và nhắc tên cả đội đã hỗ trợ mình.", s: "dan_duong" },
      { t: "Ngượng chín mặt, chỉ mong xuống nhanh.", s: "tam_guong" },
    ],
  },
  {
    id: "nd031",
    title: "Bạn vay tiền không trả",
    sit: "Đứa bạn mượn tiền 3 tháng chưa trả, vẫn check-in ăn chơi sang chảnh. Bạn cần tiền.",
    opts: [
      { t: "Nhắn thẳng đòi luôn, tiền mình mà.", s: "khoi_xuong" },
      { t: "Nhắn nhắc khéo kèm lý do mình đang cần.", s: "kien_tao" },
      { t: "Hẹn gặp nói chuyện xem họ khó khăn thật không.", s: "dan_duong" },
      { t: "Không dám đòi, sợ mất bạn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd032",
    title: "Món quà không ưng",
    sit: "Người yêu tặng áo bạn không thích chút nào, nhưng họ háo hức hỏi: “Đẹp không?”",
    opts: [
      { t: "Nói thật là không hợp gu, rủ đi đổi cùng.", s: "khoi_xuong" },
      { t: "Cảm ơn rồi cất đi, thỉnh thoảng mặc cho họ vui.", s: "kien_tao" },
      { t: "Hỏi sao họ chọn món này để hiểu ý họ.", s: "dan_duong" },
      { t: "Khen đẹp dù không thích, sợ họ buồn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd033",
    title: "Cúp điện giữa đêm",
    sit: "2h sáng cúp điện, phòng nóng hầm hập, điện thoại còn 10% pin.",
    opts: [
      { t: "Dậy ra ban công hóng gió, tiện ngắm sao.", s: "khoi_xuong" },
      { t: "Bật quạt tay, cố ngủ tiếp cho qua đêm.", s: "kien_tao" },
      { t: "Kiểm tra cầu dao và hỏi bảo vệ xem cúp lâu không.", s: "dan_duong" },
      { t: "Nằm bực bội, càng nóng càng khó chịu.", s: "tam_guong" },
    ],
  },
  {
    id: "nd034",
    title: "Lời mời việc mới",
    sit: "Công ty khác mời bạn với lương cao hơn 30%, nhưng phải thử việc lại từ đầu.",
    opts: [
      { t: "Nhận lời ngay, không thử sao biết.", s: "khoi_xuong" },
      { t: "Ở lại — ổn định và lộ trình rõ ràng hơn.", s: "kien_tao" },
      { t: "Tìm hiểu kỹ văn hóa và sếp mới rồi quyết.", s: "dan_duong" },
      { t: "Phân vân mãi vì sợ đổi rồi lại hối hận.", s: "tam_guong" },
    ],
  },
  {
    id: "nd035",
    title: "Trẻ con khóc trong quán",
    sit: "Bạn đang họp online ở quán cafe thì bàn bên trẻ con khóc ré lên không dứt.",
    opts: [
      { t: "Đổi chỗ ngay, việc mình quan trọng hơn.", s: "khoi_xuong" },
      { t: "Đeo tai nghe chống ồn, tập trung tiếp.", s: "kien_tao" },
      { t: "Nhẹ nhàng góp ý với phụ huynh.", s: "dan_duong" },
      { t: "Khó chịu mà ngại nói, họp không vào đầu chữ nào.", s: "tam_guong" },
    ],
  },
  {
    id: "nd036",
    title: "Bài đăng bị chê",
    sit: "Bạn đăng bài tâm huyết lên mạng, bình luận đầu tiên là: “Viết gì dài dòng vậy?”",
    opts: [
      { t: "Trả lời luôn: không thích thì lướt qua.", s: "khoi_xuong" },
      { t: "Kệ, ai hiểu thì hiểu, mình viết cho mình.", s: "kien_tao" },
      { t: "Xem lại bài có chỗ nào dài dòng thật không.", s: "dan_duong" },
      { t: "Buồn cả ngày, muốn xóa bài luôn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd037",
    title: "Xe hỏng giữa đường",
    sit: "Xe chết máy giữa cầu lúc 7h sáng, phía sau còi inh ỏi.",
    opts: [
      { t: "Dắt xe vào lề thật nhanh rồi tính tiếp.", s: "khoi_xuong" },
      { t: "Gọi cứu hộ quen, đứng chờ đúng chỗ an toàn.", s: "kien_tao" },
      { t: "Mở cốp kiểm tra xem bệnh gì trước.", s: "dan_duong" },
      { t: "Luống cuống, mặt đỏ vì bao ánh mắt nhìn vào.", s: "tam_guong" },
    ],
  },
  {
    id: "nd038",
    title: "Bạn thân thành công",
    sit: "Đứa bạn cùng xuất phát điểm vừa mua nhà, khoe khắp nơi. Bạn vẫn ở trọ.",
    opts: [
      { t: "Chúc mừng thật lòng rồi hỏi bí quyết của nó.", s: "khoi_xuong" },
      { t: "Lấy đó làm động lực, về cày tiếp.", s: "kien_tao" },
      { t: "Ngẫm xem mình muốn nhà hay muốn thứ khác.", s: "dan_duong" },
      { t: "Chạnh lòng, thấy mình kém cỏi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd039",
    title: "Ăn trưa một mình",
    sit: "Cả phòng rủ nhau ăn trưa mà quên rủ bạn. Bạn phát hiện khi họ đã đi.",
    opts: [
      { t: "Nhắn vào nhóm: “Đi mà không rủ tớ à, chờ với!”", s: "khoi_xuong" },
      { t: "Tự đi ăn một mình cho thoải mái.", s: "kien_tao" },
      { t: "Để ý xem họ vô tình hay cố ý.", s: "dan_duong" },
      { t: "Tủi thân, nghĩ chắc mình bị ghét.", s: "tam_guong" },
    ],
  },
  {
    id: "nd040",
    title: "Khách hàng khó tính",
    sit: "Khách yêu cầu sửa lần thứ 5, mỗi lần một ý khác nhau. Bạn đã kiệt sức.",
    opts: [
      { t: "Gọi thẳng nói rõ: chốt một phương án cuối cùng.", s: "khoi_xuong" },
      { t: "Sửa tiếp — khách hàng là thượng đế.", s: "kien_tao" },
      { t: "Hỏi khách thật sự muốn đạt điều gì rồi đề xuất lại.", s: "dan_duong" },
      { t: "Nhận sửa mà trong lòng ấm ức.", s: "tam_guong" },
    ],
  },
  {
    id: "nd041",
    title: "Mất ngủ",
    sit: "Đã 2h sáng bạn vẫn trằn trọc vì chuyện công việc ngày mai.",
    opts: [
      { t: "Dậy viết hết nỗi lo ra giấy rồi ngủ tiếp.", s: "khoi_xuong" },
      { t: "Bật nhạc nhẹ, hít thở sâu, ép mình ngủ.", s: "kien_tao" },
      { t: "Ngẫm xem điều tệ nhất có thể xảy ra là gì.", s: "dan_duong" },
      { t: "Càng nghĩ càng lo, lướt điện thoại đến sáng.", s: "tam_guong" },
    ],
  },
  {
    id: "nd042",
    title: "Quà sinh nhật cho sếp",
    sit: "Cả phòng góp tiền mua quà sinh nhật sếp, mỗi người 300 nghìn. Bạn thấy hơi nhiều.",
    opts: [
      { t: "Góp luôn cho vui vẻ, khỏi lăn tăn.", s: "khoi_xuong" },
      { t: "Góp đúng phần, không ý kiến.", s: "kien_tao" },
      { t: "Đề xuất mức góp linh hoạt theo khả năng.", s: "dan_duong" },
      { t: "Góp mà tiếc, nhưng sợ bị nói keo.", s: "tam_guong" },
    ],
  },
  {
    id: "nd043",
    title: "Phỏng vấn trượt",
    sit: "Công ty mơ ước báo bạn trượt vòng cuối. Bạn đã chuẩn bị cả tháng.",
    opts: [
      { t: "Nộp ngay 5 chỗ khác, không ngồi than.", s: "khoi_xuong" },
      { t: "Xin feedback rồi luyện tiếp cho đợt sau.", s: "kien_tao" },
      { t: "Ngẫm xem mình hợp công ty kiểu gì hơn.", s: "dan_duong" },
      { t: "Buồn bã, nghi ngờ năng lực của mình.", s: "tam_guong" },
    ],
  },
  {
    id: "nd044",
    title: "Người yêu cũ nhắn tin",
    sit: "Người yêu cũ sau 2 năm bỗng nhắn: “Dạo này sao rồi?” Bạn đang hạnh phúc với hiện tại.",
    opts: [
      { t: "Trả lời xã giao rồi thôi, không dây dưa.", s: "khoi_xuong" },
      { t: "Không trả lời — quá khứ để yên đó.", s: "kien_tao" },
      { t: "Tự hỏi họ muốn gì rồi mới quyết có rep không.", s: "dan_duong" },
      { t: "Xao xuyến cả buổi, không tập trung được.", s: "tam_guong" },
    ],
  },
  {
    id: "nd045",
    title: "Cháy nồi",
    sit: "Mải điện thoại, bạn để cháy nồi cá kho. Khói bốc mù mịt cả bếp.",
    opts: [
      { t: "Tắt bếp, mở cửa, xử lý ngay không hoảng.", s: "khoi_xuong" },
      { t: "Dọn dẹp rồi nấu nồi khác đền bù.", s: "kien_tao" },
      { t: "Rút kinh nghiệm: nấu ăn thì hẹn giờ.", s: "dan_duong" },
      { t: "Vừa dọn vừa tự trách mình đoảng.", s: "tam_guong" },
    ],
  },
  {
    id: "nd046",
    title: "Được khen bất ngờ",
    sit: "Đồng nghiệp ít nói bỗng khen: “Cách bạn xử lý vụ đó hay thật.”",
    opts: [
      { t: "Cười lớn: “Thấy chưa, tớ mà!”", s: "khoi_xuong" },
      { t: "Cảm ơn rồi làm việc tiếp như thường.", s: "kien_tao" },
      { t: "Hỏi lại xem hay ở điểm nào.", s: "dan_duong" },
      { t: "Ngượng, không biết đáp lại sao.", s: "tam_guong" },
    ],
  },
  {
    id: "nd047",
    title: "Lỡ hẹn quan trọng",
    sit: "Bạn ngủ quên, lỡ buổi gặp đối tác quan trọng. Điện thoại 5 cuộc gọi nhỡ.",
    opts: [
      { t: "Gọi lại ngay, xin lỗi và hẹn bù hôm nay.", s: "khoi_xuong" },
      { t: "Nhắn tin xin lỗi kèm phương án bù đắp cụ thể.", s: "kien_tao" },
      { t: "Gọi lại hỏi xem tình hình rồi tính.", s: "dan_duong" },
      { t: "Sợ đến mức không dám gọi lại luôn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd048",
    title: "Tiền lẻ đầu tháng",
    sit: "Đầu tháng, bạn ngồi tính toán chi tiêu. Tiền nhà, tiền ăn, tiền gửi về quê… vừa khít lương.",
    opts: [
      { t: "Kệ, tới đâu hay đó, thiếu thì cày thêm.", s: "khoi_xuong" },
      { t: "Lên bảng chi tiêu chi tiết từng khoản.", s: "kien_tao" },
      { t: "Tìm 2 khoản có thể cắt mà không ảnh hưởng nhiều.", s: "dan_duong" },
      { t: "Thở dài, thấy mình làm bao nhiêu cũng không đủ.", s: "tam_guong" },
    ],
  },
  {
    id: "nd049",
    title: "Cãi nhau với bạn thân",
    sit: "Bạn và bạn thân cãi nhau to vì chuyện tiền nong. Đã 3 ngày không ai nhắn ai.",
    opts: [
      { t: "Nhắn trước làm hòa, bạn bè quan trọng hơn.", s: "khoi_xuong" },
      { t: "Chờ vài hôm nữa cho cả hai nguội hẳn.", s: "kien_tao" },
      { t: "Nhờ đứa bạn chung đứng giữa hòa giải.", s: "dan_duong" },
      { t: "Buồn và nhớ bạn nhưng không dám nhắn trước.", s: "tam_guong" },
    ],
  },
  {
    id: "nd050",
    title: "Mưa khi đi chơi xa",
    sit: "Cả nhóm đi picnic thì trời đổ mưa. Mọi người nhìn nhau ngán ngẩm.",
    opts: [
      { t: "Đổi plan ngay: tìm quán gần nhất trú và chơi tiếp.", s: "khoi_xuong" },
      { t: "Cùng nhau dọn đồ, hẹn hôm khác đi lại.", s: "kien_tao" },
      { t: "Xem dự báo mưa bao lâu rồi quyết.", s: "dan_duong" },
      { t: "Thấy mọi người ỉu xìu nên mình cũng mất hứng.", s: "tam_guong" },
    ],
  },
  {
    id: "nd051",
    title: "Sếp mới",
    sit: "Sếp mới về, thay đổi hết quy trình bạn quen. Cả phòng xì xào.",
    opts: [
      { t: "Chủ động gặp sếp mới trao đổi thẳng.", s: "khoi_xuong" },
      { t: "Làm theo quy trình mới, thích nghi dần.", s: "kien_tao" },
      { t: "Quan sát xem sếp muốn gì rồi mới hành động.", s: "dan_duong" },
      { t: "Lo lắng, sợ mình không hợp sếp mới.", s: "tam_guong" },
    ],
  },
  {
    id: "nd052",
    title: "Đồ ăn hết hạn",
    sit: "Bạn phát hiện hộp sữa trong tủ đã hết hạn 2 ngày. Sáng nay bạn vừa uống một ly.",
    opts: [
      { t: "Vứt ngay, mua hộp mới, xong chuyện.", s: "khoi_xuong" },
      { t: "Theo dõi cơ thể, khó chịu thì đi khám.", s: "kien_tao" },
      { t: "Tìm hiểu xem quá hạn 2 ngày có sao không.", s: "dan_duong" },
      { t: "Lo lắng cả ngày dù bụng vẫn bình thường.", s: "tam_guong" },
    ],
  },
  {
    id: "nd053",
    title: "Tin đồn về mình",
    sit: "Bạn nghe phong thanh có người nói xấu mình trong công ty. Chưa rõ ai, chuyện gì.",
    opts: [
      { t: "Hỏi thẳng người kể cho mình nghe.", s: "khoi_xuong" },
      { t: "Kệ, cây ngay không sợ chết đứng.", s: "kien_tao" },
      { t: "Âm thầm tìm hiểu nguồn tin từ đâu.", s: "dan_duong" },
      { t: "Buồn và nghi ngờ tất cả mọi người.", s: "tam_guong" },
    ],
  },
  {
    id: "nd054",
    title: "Tập gym ngày đầu",
    sit: "Bạn đăng ký gym, buổi đầu huấn luyện viên xếp bài nặng. Về nhà đau ê ẩm.",
    opts: [
      { t: "Mai đi tiếp luôn, đau rồi sẽ quen.", s: "khoi_xuong" },
      { t: "Nghỉ 1 hôm rồi quay lại đúng lịch.", s: "kien_tao" },
      { t: "Bảo huấn luyện viên giảm cường độ cho phù hợp.", s: "dan_duong" },
      { t: "Muốn bỏ luôn, thấy mình không hợp vận động.", s: "tam_guong" },
    ],
  },
  {
    id: "nd055",
    title: "Con ốm",
    sit: "Nửa đêm con sốt cao, quấy khóc không dứt. Nhà chỉ có hai vợ chồng.",
    opts: [
      { t: "Đưa con đi viện ngay cho yên tâm.", s: "khoi_xuong" },
      { t: "Hạ sốt, chườm khăn, thay nhau thức trông.", s: "kien_tao" },
      { t: "Gọi bác sĩ quen hỏi trước rồi quyết.", s: "dan_duong" },
      { t: "Hoảng loạn, tay chân luống cuống.", s: "tam_guong" },
    ],
  },
  {
    id: "nd056",
    title: "Hóa đơn nhầm",
    sit: "Quán tính nhầm hóa đơn cao hơn 200 nghìn. Bạn phát hiện khi đã ra khỏi quán.",
    opts: [
      { t: "Quay lại nói ngay với quán.", s: "khoi_xuong" },
      { t: "Gọi điện báo quán, hôm sau ghé lấy lại.", s: "kien_tao" },
      { t: "Chụp hóa đơn, kiểm tra kỹ rồi mới quay lại.", s: "dan_duong" },
      { t: "Tiếc tiền nhưng ngại quay lại đòi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd057",
    title: "Cuộc gọi lừa đảo",
    sit: "Số lạ gọi báo bạn dính án, yêu cầu chuyển tiền “chứng minh vô tội”. Giọng rất nghiêm.",
    opts: [
      { t: "Cúp máy ngay, chặn số luôn.", s: "khoi_xuong" },
      { t: "Bình tĩnh nghe hết rồi báo công an.", s: "kien_tao" },
      { t: "Hỏi vặn lại thông tin để lật tẩy chúng.", s: "dan_duong" },
      { t: "Hoảng sợ, suýt làm theo lời chúng.", s: "tam_guong" },
    ],
  },
  {
    id: "nd058",
    title: "Nhà bừa bộn",
    sit: "Cuối tuần nhìn quanh nhà: quần áo chất đống, bát đĩa ngập bồn. Bạn thở dài.",
    opts: [
      { t: "Bật nhạc to, dọn một mạch 2 tiếng.", s: "khoi_xuong" },
      { t: "Dọn từng khu, xong khu nào gọn khu đó.", s: "kien_tao" },
      { t: "Lên danh sách việc rồi dọn theo thứ tự.", s: "dan_duong" },
      { t: "Nhìn thôi đã nản, để mai tính.", s: "tam_guong" },
    ],
  },
  {
    id: "nd059",
    title: "Bạn khoe người yêu mới",
    sit: "Bạn thân khoe người yêu mới giàu và chiều. Bạn đang độc thân vui vẻ… hoặc tự nhủ thế.",
    opts: [
      { t: "Chúc mừng rồi rủ cả hai đi ăn.", s: "khoi_xuong" },
      { t: "Mừng cho bạn, mình lo sự nghiệp trước.", s: "kien_tao" },
      { t: "Hỏi han xem họ quen nhau thế nào.", s: "dan_duong" },
      { t: "Ngoài cười trong tủi, tối về thấy cô đơn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd060",
    title: "Thi trượt bằng lái",
    sit: "Bạn trượt sa hình lần 2. Thầy giáo lắc đầu, bạn bè cười trêu.",
    opts: [
      { t: "Đăng ký thi lại ngay tuần sau.", s: "khoi_xuong" },
      { t: "Thuê thêm giờ tập rồi mới thi.", s: "kien_tao" },
      { t: "Xem lại mình yếu ở phần nào để tập trung.", s: "dan_duong" },
      { t: "Xấu hổ, muốn bỏ luôn không thi nữa.", s: "tam_guong" },
    ],
  },
  {
    id: "nd061",
    title: "Mất chìa khóa",
    sit: "Đứng trước cửa nhà mới phát hiện mất chùm chìa khóa. Trời đã tối.",
    opts: [
      { t: "Gọi thợ khóa đến ngay.", s: "khoi_xuong" },
      { t: "Sang nhà hàng xóm gửi nhờ, mai tính.", s: "kien_tao" },
      { t: "Nhớ lại cả ngày đi đâu để tìm.", s: "dan_duong" },
      { t: "Đứng thở dài, trách mình đãng trí.", s: "tam_guong" },
    ],
  },
  {
    id: "nd062",
    title: "Ăn kiêng ngày 3",
    sit: "Bạn đang ăn kiêng thì đồng nghiệp mang bánh tráng trộn đến mời cả phòng. Mùi thơm phức.",
    opts: [
      { t: "Ăn luôn một ít, kiêng gì mai kiêng.", s: "khoi_xuong" },
      { t: "Từ chối — đã quyết thì theo đến cùng.", s: "kien_tao" },
      { t: "Ăn một miếng cho vui rồi dừng.", s: "dan_duong" },
      { t: "Thấy ai cũng ăn nên cũng ăn theo luôn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd063",
    title: "Bố mẹ giục cưới",
    sit: "Tết về quê, họ hàng thay nhau hỏi: “Bao giờ cưới?” Bạn 28 tuổi, chưa người yêu.",
    opts: [
      { t: "Cười đáp: “Khi nào vui thì cưới, cả nhà đừng lo!”", s: "khoi_xuong" },
      { t: "Nghe tai này qua tai kia, ăn tiếp.", s: "kien_tao" },
      { t: "Hỏi lại xem mọi người lo điều gì cho mình.", s: "dan_duong" },
      { t: "Ăn mất ngon, Tết mà thấy áp lực.", s: "tam_guong" },
    ],
  },
  {
    id: "nd064",
    title: "Máy tính đơ",
    sit: "Máy tính đơ đúng lúc bạn đang làm báo cáo quan trọng, chưa kịp lưu.",
    opts: [
      { t: "Khởi động lại ngay, mất thì làm lại.", s: "khoi_xuong" },
      { t: "Chờ một lúc, thử mọi cách trước khi tắt máy.", s: "kien_tao" },
      { t: "Tìm xem file tự lưu ở đâu trước đã.", s: "dan_duong" },
      { t: "Hoảng, chỉ sợ mất hết công sức.", s: "tam_guong" },
    ],
  },
  {
    id: "nd065",
    title: "Chuyển nhà",
    sit: "Chủ trọ báo tăng giá 20%. Tìm nhà mới thì mệt, ở lại thì tiếc tiền.",
    opts: [
      { t: "Dọn luôn, ở đâu chẳng là ở.", s: "khoi_xuong" },
      { t: "Ở lại cho ổn định, đi làm gần.", s: "kien_tao" },
      { t: "Thương lượng với chủ trọ trước rồi quyết.", s: "dan_duong" },
      { t: "Phân vân mãi không quyết được.", s: "tam_guong" },
    ],
  },
  {
    id: "nd066",
    title: "Xem phim bị spoil",
    sit: "Đứa bạn vô tư spoil cái kết phim bạn để dành cả tuần. Bạn đang xem dở tập 5.",
    opts: [
      { t: "Mắng nó một trận cho hả giận.", s: "khoi_xuong" },
      { t: "Kệ, xem tiếp vì thích diễn xuất.", s: "kien_tao" },
      { t: "Hỏi nó spoil thật hay đùa.", s: "dan_duong" },
      { t: "Mất hứng xem tiếp luôn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd067",
    title: "Lương về chậm",
    sit: "Quá ngày lương 5 hôm công ty vẫn chưa trả, hỏi kế toán thì bảo “chờ sếp duyệt”.",
    opts: [
      { t: "Hỏi thẳng sếp luôn cho rõ.", s: "khoi_xuong" },
      { t: "Chờ thêm vài hôm, công ty khó khăn chung.", s: "kien_tao" },
      { t: "Hỏi đồng nghiệp xem ai cũng bị thế không.", s: "dan_duong" },
      { t: "Lo lắng nhưng không dám hỏi ai.", s: "tam_guong" },
    ],
  },
  {
    id: "nd068",
    title: "Quên tắt bếp gas",
    sit: "Ra khỏi nhà 10 phút mới nhớ không chắc đã tắt bếp gas chưa.",
    opts: [
      { t: "Quay về kiểm tra ngay cho chắc.", s: "khoi_xuong" },
      { t: "Nhờ người nhà ghé qua xem giúp.", s: "kien_tao" },
      { t: "Ngồi nhớ lại từng thao tác lúc ra khỏi nhà.", s: "dan_duong" },
      { t: "Lo lắng cả buổi mà không dám quay về.", s: "tam_guong" },
    ],
  },
  {
    id: "nd069",
    title: "Bạn mượn đồ không trả",
    sit: "Bạn mượn cuốn sách quý của bạn 2 tháng chưa trả, hỏi thì bảo “để quên ở quê”.",
    opts: [
      { t: "Đòi thẳng, sách quý không đùa được.", s: "khoi_xuong" },
      { t: "Nhắc nhẹ rồi cho thêm thời gian.", s: "kien_tao" },
      { t: "Hỏi xem họ có định trả không để tính.", s: "dan_duong" },
      { t: "Tiếc sách mà ngại đòi, đành thôi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd070",
    title: "Trời đẹp bất ngờ",
    sit: "Sáng cuối tuần trời trong xanh, gió mát — đẹp nhất cả tháng nay.",
    opts: [
      { t: "Ra khỏi nhà ngay, trời đẹp không chờ ai.", s: "khoi_xuong" },
      { t: "Tranh thủ giặt giũ, phơi đồ.", s: "kien_tao" },
      { t: "Rủ bạn bè xem ai rảnh đi đâu đó.", s: "dan_duong" },
      { t: "Ngắm qua cửa sổ rồi nằm tiếp.", s: "tam_guong" },
    ],
  },
  {
    id: "nd071",
    title: "Bị trừ lương oan",
    sit: "Bảng lương trừ của bạn 1 ngày công “đi trễ” mà bạn chắc chắn mình đúng giờ.",
    opts: [
      { t: "Lên phòng nhân sự hỏi ngay hôm nay.", s: "khoi_xuong" },
      { t: "Thu thập bằng chứng chấm công rồi mới lên tiếng.", s: "kien_tao" },
      { t: "Hỏi đồng nghiệp xem ai cũng bị thế không.", s: "dan_duong" },
      { t: "Tức mà sợ lên tiếng bị ghét nên thôi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd072",
    title: "Người yêu quên kỷ niệm",
    sit: "Kỷ niệm 2 năm yêu nhau mà người yêu quên béng, tối còn rủ đi nhậu với bạn.",
    opts: [
      { t: "Nói thẳng là mình buồn, không vòng vo.", s: "khoi_xuong" },
      { t: "Tự tổ chức bất ngờ để nhắc khéo họ.", s: "kien_tao" },
      { t: "Chờ xem họ có nhớ ra không đã.", s: "dan_duong" },
      { t: "Giận dỗi cả tuần không nói gì.", s: "tam_guong" },
    ],
  },
  {
    id: "nd073",
    title: "Học thêm ngoại ngữ",
    sit: "Bạn quyết tâm học tiếng Anh, mua sách vở đầy đủ. Đến ngày thứ 3 thì lười.",
    opts: [
      { t: "Đăng ký luôn khóa học có thầy để khỏi lười.", s: "khoi_xuong" },
      { t: "Ép mình học 30 phút mỗi ngày, mưa cũng học.", s: "kien_tao" },
      { t: "Tìm phương pháp học vui hơn thay vì ép.", s: "dan_duong" },
      { t: "Bỏ luôn, hẹn “tháng sau bắt đầu lại”.", s: "tam_guong" },
    ],
  },
  {
    id: "nd074",
    title: "Thú cưng ốm",
    sit: "Con mèo bạn nuôi bỏ ăn 2 ngày, nằm một chỗ. Bạn lo đến mất ngủ.",
    opts: [
      { t: "Bế đi thú y ngay sáng mai.", s: "khoi_xuong" },
      { t: "Đút ăn, theo dõi từng giờ.", s: "kien_tao" },
      { t: "Hỏi hội nuôi mèo xem triệu chứng này là gì.", s: "dan_duong" },
      { t: "Khóc vì thương mà chưa biết làm gì.", s: "tam_guong" },
    ],
  },
  {
    id: "nd075",
    title: "Đi chợ trả giá",
    sit: "Bà bán rau hét giá gấp đôi mọi hôm. Bạn biết rõ giá thật.",
    opts: [
      { t: "Trả đúng giá, không bán thì sang hàng khác.", s: "khoi_xuong" },
      { t: "Mua luôn cho nhanh, hơn thua vài nghìn.", s: "kien_tao" },
      { t: "Hỏi sao hôm nay đắt thế rồi mặc cả.", s: "dan_duong" },
      { t: "Ngại trả giá nên mua luôn giá cao.", s: "tam_guong" },
    ],
  },
  {
    id: "nd076",
    title: "Mất ngủ trước ngày quan trọng",
    sit: "Mai bạn thuyết trình trước ban lãnh đạo. Đã 1h sáng mà mắt vẫn mở thao láo.",
    opts: [
      { t: "Dậy duyệt lại slide một lượt cho yên tâm.", s: "khoi_xuong" },
      { t: "Uống sữa ấm, tắt đèn, ép ngủ.", s: "kien_tao" },
      { t: "Tưởng tượng buổi thuyết trình suôn sẻ để trấn an.", s: "dan_duong" },
      { t: "Càng lo càng tỉnh, lướt điện thoại đến sáng.", s: "tam_guong" },
    ],
  },
  {
    id: "nd077",
    title: "Bạn rủ đầu tư",
    sit: "Bạn thân rủ góp vốn mở quán cafe, nói “chắc thắng”. Cần 100 triệu.",
    opts: [
      { t: "Góp luôn, tin bạn là chính.", s: "khoi_xuong" },
      { t: "Từ chối — tiền mồ hôi không liều được.", s: "kien_tao" },
      { t: "Xin xem kế hoạch kinh doanh chi tiết đã.", s: "dan_duong" },
      { t: "Muốn từ chối mà sợ bạn giận.", s: "tam_guong" },
    ],
  },
  {
    id: "nd078",
    title: "Quên tên người quen",
    sit: "Gặp người quen ở siêu thị, họ chào bạn thân thiết mà bạn quên mất tên họ.",
    opts: [
      { t: "Hỏi thẳng: “Xin lỗi, tên bạn là gì nhỉ?”", s: "khoi_xuong" },
      { t: "Chào chung chung, tránh gọi tên.", s: "kien_tao" },
      { t: "Gợi chuyện để họ tự xưng tên.", s: "dan_duong" },
      { t: "Ngượng chín mặt, tìm cách chuồn nhanh.", s: "tam_guong" },
    ],
  },
  {
    id: "nd079",
    title: "Nước ngập vào nhà",
    sit: "Mưa to, nước bắt đầu tràn vào nhà. Đồ điện tử còn để dưới thấp.",
    opts: [
      { t: "Kê đồ lên cao ngay, chạy đua với nước.", s: "khoi_xuong" },
      { t: "Bình tĩnh dọn từng thứ theo giá trị.", s: "kien_tao" },
      { t: "Chặn cửa trước rồi mới dọn đồ.", s: "dan_duong" },
      { t: "Hoảng, không biết bắt đầu từ đâu.", s: "tam_guong" },
    ],
  },
  {
    id: "nd080",
    title: "Được tăng lương ít",
    sit: "Bạn kỳ vọng tăng 20%, công ty tăng 5%. Sếp bảo “tình hình chung”.",
    opts: [
      { t: "Đề xuất thẳng con số mình muốn.", s: "khoi_xuong" },
      { t: "Chấp nhận, cố gắng hơn năm sau.", s: "kien_tao" },
      { t: "Hỏi rõ tiêu chí đánh giá của mình.", s: "dan_duong" },
      { t: "Buồn nhưng không dám nói gì.", s: "tam_guong" },
    ],
  },
  {
    id: "nd081",
    title: "Tiệc công ty",
    sit: "Tiệc cuối năm, sếp gọi bạn lên hát góp vui. Bạn hát dở tệ.",
    opts: [
      { t: "Lên hát luôn, vui là chính.", s: "khoi_xuong" },
      { t: "Từ chối khéo, xung phong việc khác.", s: "kien_tao" },
      { t: "Rủ thêm đồng nghiệp lên hát cùng.", s: "dan_duong" },
      { t: "Ngượng đỏ mặt, chỉ mong qua nhanh.", s: "tam_guong" },
    ],
  },
  {
    id: "nd082",
    title: "Con điểm kém",
    sit: "Con bạn bị điểm 4 môn Toán, giấu không dám nói. Bạn phát hiện trong cặp.",
    opts: [
      { t: "Gọi con ra nói chuyện ngay tối nay.", s: "khoi_xuong" },
      { t: "Thuê gia sư, kèm con học lại từ đầu.", s: "kien_tao" },
      { t: "Hỏi con gặp khó ở đâu trước đã.", s: "dan_duong" },
      { t: "Buồn và lo, sợ con thua bạn bè.", s: "tam_guong" },
    ],
  },
  {
    id: "nd083",
    title: "Wifi chập chờn",
    sit: "Đang họp online quan trọng thì wifi chập chờn, màn hình đứng hình.",
    opts: [
      { t: "Bật 4G phát ngay, không chờ.", s: "khoi_xuong" },
      { t: "Nhắn xin lỗi cả nhóm, out ra vào lại.", s: "kien_tao" },
      { t: "Kiểm tra xem do mạng hay do máy.", s: "dan_duong" },
      { t: "Luống cuống, sợ mọi người đánh giá.", s: "tam_guong" },
    ],
  },
  {
    id: "nd084",
    title: "Bạn mượn xe",
    sit: "Bạn hỏi mượn xe máy 1 tuần đi tỉnh. Xe bạn mới mua 2 tháng.",
    opts: [
      { t: "Cho mượn luôn, bạn bè tin nhau.", s: "khoi_xuong" },
      { t: "Từ chối khéo — xe mới xót lắm.", s: "kien_tao" },
      { t: "Hỏi kỹ đi đâu, đi với ai rồi quyết.", s: "dan_duong" },
      { t: "Không muốn mà không dám từ chối.", s: "tam_guong" },
    ],
  },
  {
    id: "nd085",
    title: "Ăn khuya",
    sit: "11h đêm bụng đói cồn cào, tủ lạnh còn mì gói. Bạn đang giảm cân.",
    opts: [
      { t: "Nấu ăn luôn, đói không ngủ được.", s: "khoi_xuong" },
      { t: "Uống nước rồi đi ngủ, mai ăn bù.", s: "kien_tao" },
      { t: "Ăn nhẹ nửa gói cho đỡ đói.", s: "dan_duong" },
      { t: "Vừa ăn vừa thấy tội lỗi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd086",
    title: "Sếp khen riêng",
    sit: "Sếp nhắn riêng khen bạn làm tốt và úp mở chuyện thăng chức cuối năm.",
    opts: [
      { t: "Hỏi luôn cần làm gì để chắc suất.", s: "khoi_xuong" },
      { t: "Cảm ơn rồi cày tiếp, không chủ quan.", s: "kien_tao" },
      { t: "Tìm hiểu xem còn ai trong diện nữa.", s: "dan_duong" },
      { t: "Vui nhưng lo, sợ hy vọng rồi thất vọng.", s: "tam_guong" },
    ],
  },
  {
    id: "nd087",
    title: "Trễ chuyến bay",
    sit: "Tắc đường, bạn đến sân bay trễ 10 phút, cổng đã đóng. Vé không hoàn được.",
    opts: [
      { t: "Chạy ngay quầy vé đổi chuyến kế tiếp.", s: "khoi_xuong" },
      { t: "Bình tĩnh mua vé mới, coi như bài học.", s: "kien_tao" },
      { t: "Hỏi nhân viên còn cách nào cứu không.", s: "dan_duong" },
      { t: "Đứng sững, tiếc tiền đến muốn khóc.", s: "tam_guong" },
    ],
  },
  {
    id: "nd088",
    title: "Nhà có khách bất ngờ",
    sit: "Họ hàng từ quê lên thăm không báo trước, nhà bạn thì bừa bộn, tủ lạnh trống.",
    opts: [
      { t: "Dẫn cả nhà ra quán ăn luôn cho nhanh.", s: "khoi_xuong" },
      { t: "Chạy đi chợ nấu một bữa tử tế.", s: "kien_tao" },
      { t: "Hỏi khách muốn ăn gì rồi tính.", s: "dan_duong" },
      { t: "Luống cuống, xấu hổ vì nhà bừa.", s: "tam_guong" },
    ],
  },
  {
    id: "nd089",
    title: "Bị so sánh",
    sit: "Trong họp gia đình, bác khen anh họ thăng tiến rồi quay sang: “Cháu thì sao?”",
    opts: [
      { t: "Đáp vui: “Cháu đi đường khác, cũng sắp tới nơi rồi!”", s: "khoi_xuong" },
      { t: "Cười trừ, về nhà cày tiếp.", s: "kien_tao" },
      { t: "Hỏi anh họ xem làm thế nào để học hỏi.", s: "dan_duong" },
      { t: "Ăn mất ngon cả bữa.", s: "tam_guong" },
    ],
  },
  {
    id: "nd090",
    title: "Điện thoại rơi vỡ",
    sit: "Điện thoại rơi vỡ màn hình, sửa mất 2 triệu. Máy bạn mua chưa đầy năm.",
    opts: [
      { t: "Mang đi sửa ngay hôm nay.", s: "khoi_xuong" },
      { t: "Dán tạm dùng tiếp, dành tiền việc khác.", s: "kien_tao" },
      { t: "So giá 2-3 chỗ rồi mới sửa.", s: "dan_duong" },
      { t: "Xót tiền, trách mình bất cẩn mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd091",
    title: "Lời tỏ tình",
    sit: "Người bạn thích 2 năm bỗng tỏ tình. Tim bạn đập như trống.",
    opts: [
      { t: "Đồng ý ngay, chờ gì nữa!", s: "khoi_xuong" },
      { t: "Xin thời gian suy nghĩ cho chắc.", s: "kien_tao" },
      { t: "Hỏi rõ tình cảm của họ thế nào.", s: "dan_duong" },
      { t: "Bối rối, không biết trả lời sao.", s: "tam_guong" },
    ],
  },
  {
    id: "nd092",
    title: "Dọn tủ quần áo",
    sit: "Tủ quần áo chật cứng, nhiều món 2 năm không mặc. Bạn quyết định dọn.",
    opts: [
      { t: "Cho hết vào bao mang đi từ thiện luôn.", s: "khoi_xuong" },
      { t: "Phân loại từng món: giữ, cho, bỏ.", s: "kien_tao" },
      { t: "Thử lại từng món rồi mới quyết.", s: "dan_duong" },
      { t: "Cầm món nào cũng tiếc, cuối cùng giữ hết.", s: "tam_guong" },
    ],
  },
  {
    id: "nd093",
    title: "Bị chê ngoại hình",
    sit: "Người quen buột miệng: “Dạo này béo ra đấy.” Bạn đang nhạy cảm về cân nặng.",
    opts: [
      { t: "Đáp lại ngay: “Vui là được, lo gì!”", s: "khoi_xuong" },
      { t: "Cười trừ, về nhà siết lại chế độ ăn.", s: "kien_tao" },
      { t: "Hỏi xem mình thay đổi nhiều lắm không.", s: "dan_duong" },
      { t: "Buồn cả ngày, soi gương mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd094",
    title: "Mất điện thoại trên taxi",
    sit: "Xuống taxi 5 phút mới nhớ bỏ quên điện thoại trên xe. Không nhớ hãng xe.",
    opts: [
      { t: "Gọi ngay vào máy mình, hy vọng tài xế nghe.", s: "khoi_xuong" },
      { t: "Dùng tính năng tìm máy từ máy tính.", s: "kien_tao" },
      { t: "Nhớ lại biển số, màu xe rồi báo tổng đài.", s: "dan_duong" },
      { t: "Hoảng loạn, nghĩ chắc mất luôn rồi.", s: "tam_guong" },
    ],
  },
  {
    id: "nd095",
    title: "Ngày lễ một mình",
    sit: "Lễ này bạn không về quê được, ở lại thành phố một mình. Ai cũng đi chơi.",
    opts: [
      { t: "Tự thưởng một chuyến đi gần, một mình cũng đi.", s: "khoi_xuong" },
      { t: "Ở nhà nghỉ ngơi, làm việc tồn.", s: "kien_tao" },
      { t: "Rủ xem còn ai ở lại không rồi tụ tập.", s: "dan_duong" },
      { t: "Thấy cô đơn, lướt ảnh người ta mà buồn.", s: "tam_guong" },
    ],
  },
  {
    id: "nd096",
    title: "Bị đòi nợ nhầm",
    sit: "Chủ nợ của người tên giống hệt bạn gọi điện đòi tiền, giọng hăm dọa.",
    opts: [
      { t: "Nói rõ họ nhầm người rồi cúp máy.", s: "khoi_xuong" },
      { t: "Bình tĩnh giải thích và cung cấp thông tin.", s: "kien_tao" },
      { t: "Hỏi lại thông tin khoản nợ để đối chiếu.", s: "dan_duong" },
      { t: "Sợ run dù biết không phải mình.", s: "tam_guong" },
    ],
  },
  {
    id: "nd097",
    title: "Con hỏi khó",
    sit: "Con 6 tuổi hỏi: “Sao bố mẹ phải đi làm mà không ở nhà chơi với con?”",
    opts: [
      { t: "Ôm con: “Để cuối tuần bố mẹ đưa con đi chơi!”", s: "khoi_xuong" },
      { t: "Giải thích đơn giản về công việc và trách nhiệm.", s: "kien_tao" },
      { t: "Hỏi lại: “Con muốn bố mẹ ở nhà làm gì nào?”", s: "dan_duong" },
      { t: "Nghe mà thấy có lỗi với con vô cùng.", s: "tam_guong" },
    ],
  },
  {
    id: "nd098",
    title: "Hết tiền giữa tháng",
    sit: "Mới ngày 15 mà tài khoản chỉ còn 500 nghìn. Còn nửa tháng nữa mới có lương.",
    opts: [
      { t: "Nhận việc làm thêm ngay, ngồi lo không ra tiền.", s: "khoi_xuong" },
      { t: "Thắt chặt chi tiêu, ăn cơm nhà cả nửa tháng.", s: "kien_tao" },
      { t: "Ngồi tính lại xem tiền đi đâu để rút kinh nghiệm.", s: "dan_duong" },
      { t: "Stress, thấy mình kém cỏi chuyện tiền bạc.", s: "tam_guong" },
    ],
  },
  {
    id: "nd099",
    title: "Lời xin lỗi muộn",
    sit: "Người từng làm tổn thương bạn nhắn xin lỗi sau 3 năm. Bạn đã quên gần hết.",
    opts: [
      { t: "Tha thứ ngay, nhẹ lòng cả hai.", s: "khoi_xuong" },
      { t: "Nhận lời xin lỗi nhưng giữ khoảng cách.", s: "kien_tao" },
      { t: "Hỏi sao giờ mới nói rồi mới quyết.", s: "dan_duong" },
      { t: "Đọc xong khóc, bao cảm xúc cũ ùa về.", s: "tam_guong" },
    ],
  },
  {
    id: "nd100",
    title: "Ước mơ dang dở",
    sit: "Đêm khuya, bạn chợt nhớ ước mơ năm 20 tuổi mình bỏ dở. Giờ bạn 30.",
    opts: [
      { t: "Lên kế hoạch bắt đầu lại ngay tháng này.", s: "khoi_xuong" },
      { t: "Dành mỗi tối 1 tiếng theo đuổi dần.", s: "kien_tao" },
      { t: "Ngẫm xem ước mơ đó còn hợp mình không.", s: "dan_duong" },
      { t: "Buồn và tiếc, nghĩ chắc đã quá muộn.", s: "tam_guong" },
    ],
  },
];
