import type { BankQuestion } from "./bank";

// Kho 100 câu concept Linh Thú: khu rừng thần thoại, ẩn dụ qua hành trình.
export const BANK_LINH_THU: BankQuestion[] = [
  {
    id: "lt001",
    title: "Cổng rừng",
    sit: "Trước mặt bạn là cổng rừng phủ rêu, bên trong tối om và vang tiếng lạ. Không ai đi cùng.",
    opts: [
      { t: "Bước vào luôn, sợ thì ở nhà.", s: "khoi_xuong" },
      { t: "Chuẩn bị đuốc và lương khô rồi mới vào.", s: "kien_tao" },
      { t: "Đứng nghe ngóng xem tiếng đó là gì.", s: "dan_duong" },
      { t: "Rùng mình, muốn quay về.", s: "tam_guong" },
    ],
  },
  {
    id: "lt002",
    title: "Ngã ba suối",
    sit: "Con suối chia hai nhánh: một êm đềm, một cuồn cuộn bọt trắng. Bạn cần qua bờ bên kia.",
    opts: [
      { t: "Lội qua nhánh êm, chậm mà chắc.", s: "kien_tao" },
      { t: "Quan sát dòng chảy rồi chọn điểm cạn nhất.", s: "dan_duong" },
      { t: "Sợ nước nên đứng mãi không dám qua.", s: "tam_guong" },
      { t: "Nhảy qua nhánh xiết cho nhanh.", s: "khoi_xuong" },
    ],
  },
  {
    id: "lt003",
    title: "Tiếng gọi trong sương",
    sit: "Sương mù dày đặc, có tiếng gọi tên bạn từ xa. Nghe như giọng người thân.",
    opts: [
      { t: "Chạy theo tiếng gọi ngay.", s: "khoi_xuong" },
      { t: "Đứng yên, gọi to đáp lại trước.", s: "kien_tao" },
      { t: "Lắng nghe xem tiếng thật hay ảo.", s: "dan_duong" },
      { t: "Sởn gai ốc, tim đập thình thịch.", s: "tam_guong" },
    ],
  },
  {
    id: "lt004",
    title: "Cây cổ thụ",
    sit: "Cây khổng lồ chắn ngang đường, tán lá thì thầm như đang nói. Vòng qua thì xa gấp ba.",
    opts: [
      { t: "Trèo qua luôn cho nhanh.", s: "khoi_xuong" },
      { t: "Đi vòng, tôn trọng rừng.", s: "kien_tao" },
      { t: "Dừng lại nghe xem cây muốn nói gì.", s: "dan_duong" },
      { t: "Thấy rờn rợn, không dám lại gần.", s: "tam_guong" },
    ],
  },
  {
    id: "lt005",
    title: "Bầy sói",
    sit: "Bầy sói 5 con chặn đường, mắt sáng rực. Chạy thì không kịp, trèo cây thì cây xa.",
    opts: [
      { t: "Giơ đuốc tiến tới, hét lớn dọa chúng.", s: "khoi_xuong" },
      { t: "Đứng yên, từ từ lùi lại.", s: "kien_tao" },
      { t: "Quan sát con đầu đàn để đoán ý cả bầy.", s: "dan_duong" },
      { t: "Chân run, chỉ biết cầu nguyện.", s: "tam_guong" },
    ],
  },
  {
    id: "lt006",
    title: "Hồ gương",
    sit: "Mặt hồ phẳng như gương, in rõ hình bạn nhưng… già hơn 20 tuổi. Gió lặng như tờ.",
    opts: [
      { t: "Nhúng tay xuống xem có gì.", s: "khoi_xuong" },
      { t: "Ngồi lại ngẫm về chặng đường mình đi.", s: "kien_tao" },
      { t: "Đi quanh hồ tìm xem có gì lạ.", s: "dan_duong" },
      { t: "Buồn man mác, thấy thời gian trôi nhanh quá.", s: "tam_guong" },
    ],
  },
  {
    id: "lt007",
    title: "Hang tối",
    sit: "Lối đi duy nhất xuyên qua hang tối om, sâu hun hút. Từ trong vọng ra tiếng nước nhỏ giọt.",
    opts: [
      { t: "Đốt đuốc đi thẳng vào.", s: "khoi_xuong" },
      { t: "Buộc dây vào cửa hang rồi mới vào.", s: "kien_tao" },
      { t: "Ném đá vào nghe vang để đoán độ sâu.", s: "dan_duong" },
      { t: "Sợ bóng tối nên chần chừ mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt008",
    title: "Quả lạ",
    sit: "Cây trĩu quả vàng óng, thơm phức. Bảng gỗ cũ ghi: “Ăn một quả, đổi một ký ức”.",
    opts: [
      { t: "Ăn luôn, ký ức cũ giữ làm gì.", s: "khoi_xuong" },
      { t: "Không ăn — cái gì cũng có giá của nó.", s: "kien_tao" },
      { t: "Hỏi xem đổi ký ức nào rồi mới ăn.", s: "dan_duong" },
      { t: "Thèm mà sợ, đứng nhìn mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt009",
    title: "Cầu treo",
    sit: "Cầu treo cũ nát bắc qua vực sâu. Gió thổi cầu đung đưa. Bên kia là ánh lửa trại.",
    opts: [
      { t: "Chạy qua luôn, càng nhanh càng đỡ sợ.", s: "khoi_xuong" },
      { t: "Bò chậm từng bước, bám chắc dây.", s: "kien_tao" },
      { t: "Kiểm tra từng tấm ván trước khi bước.", s: "dan_duong" },
      { t: "Nhìn xuống vực đã chóng mặt.", s: "tam_guong" },
    ],
  },
  {
    id: "lt010",
    title: "Lửa trại lạ",
    sit: "Giữa rừng có đống lửa trại còn cháy mà không một bóng người. Bên cạnh là nồi súp thơm.",
    opts: [
      { t: "Ngồi xuống ăn luôn, đói rồi.", s: "khoi_xuong" },
      { t: "Không động vào đồ không phải của mình.", s: "kien_tao" },
      { t: "Quan sát dấu vết xem ai vừa ở đây.", s: "dan_duong" },
      { t: "Thấy ấm áp mà cũng thấy sợ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt011",
    title: "Con cú trắng",
    sit: "Cú trắng đậu trên cành nhìn bạn chằm chằm, rồi bay về hướng ngược đường bạn định đi.",
    opts: [
      { t: "Đi theo cú xem nó dẫn đi đâu.", s: "khoi_xuong" },
      { t: "Đi đường mình đã định, không mê tín.", s: "kien_tao" },
      { t: "Dừng lại xem đó là điềm gì.", s: "dan_duong" },
      { t: "Rờn rợn, thấy như bị theo dõi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt012",
    title: "Thác nước",
    sit: "Thác cao đổ ầm ầm, sau màn nước thấp thoáng cửa hang. Muốn vào phải bơi qua hồ xoáy.",
    opts: [
      { t: "Nhảy xuống bơi qua luôn.", s: "khoi_xuong" },
      { t: "Tìm đường vòng an toàn hơn.", s: "kien_tao" },
      { t: "Ném cành cây xem xoáy mạnh cỡ nào.", s: "dan_duong" },
      { t: "Đẹp mà sợ, chỉ dám đứng nhìn.", s: "tam_guong" },
    ],
  },
  {
    id: "lt013",
    title: "Đom đóm dẫn đường",
    sit: "Đàn đom đóm xếp thành hàng bay về phía trái, trong khi bản đồ chỉ đi phải.",
    opts: [
      { t: "Theo đom đóm, rừng biết đường hơn giấy.", s: "khoi_xuong" },
      { t: "Theo bản đồ, không tin chuyện huyền hoặc.", s: "kien_tao" },
      { t: "Đi một đoạn theo đom đóm xem sao.", s: "dan_duong" },
      { t: "Phân vân không biết tin ai.", s: "tam_guong" },
    ],
  },
  {
    id: "lt014",
    title: "Rắn hổ mang",
    sit: "Rắn hổ mang ngóc đầu giữa đường, phì phò đe dọa. Quanh bạn không có gậy.",
    opts: [
      { t: "Dậm chân, hét lớn đuổi nó đi.", s: "kien_tao" },
      { t: "Đứng im chờ nó bỏ đi.", s: "dan_duong" },
      { t: "Sợ cứng người, không nhúc nhích nổi.", s: "tam_guong" },
      { t: "Nhảy qua luôn cho nhanh.", s: "khoi_xuong" },
    ],
  },
  {
    id: "lt015",
    title: "Túp lều phù thủy",
    sit: "Túp lều bốc khói thơm, bà lão mời vào uống trà. Mắt bà sáng lạ thường.",
    opts: [
      { t: "Vào luôn, có gì mà sợ.", s: "khoi_xuong" },
      { t: "Cảm ơn rồi đi tiếp, không dây vào.", s: "kien_tao" },
      { t: "Hỏi bà vài câu trước khi vào.", s: "dan_duong" },
      { t: "Vừa tò mò vừa sợ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt016",
    title: "Vực thẳm",
    sit: "Đường cụt ở miệng vực, dưới sâu là mây. Có dây thừng cũ buộc sẵn vào gốc cây.",
    opts: [
      { t: "Bám dây tụt xuống luôn.", s: "khoi_xuong" },
      { t: "Quay lại tìm đường khác.", s: "kien_tao" },
      { t: "Giật thử dây xem chắc không đã.", s: "dan_duong" },
      { t: "Nhìn xuống đã bủn rủn chân tay.", s: "tam_guong" },
    ],
  },
  {
    id: "lt017",
    title: "Tiếng khóc trẻ con",
    sit: "Nửa đêm trong rừng vang tiếng trẻ con khóc. Bạn biết quanh đây không có làng nào.",
    opts: [
      { t: "Chạy về phía tiếng khóc xem sao.", s: "khoi_xuong" },
      { t: "Ở yên trong lều, sáng tính.", s: "kien_tao" },
      { t: "Lắng nghe xem tiếng từ hướng nào, xa hay gần.", s: "dan_duong" },
      { t: "Trùm chăn run cầm cập.", s: "tam_guong" },
    ],
  },
  {
    id: "lt018",
    title: "Bản đồ kho báu",
    sit: "Bạn nhặt được nửa tấm bản đồ kho báu, nửa kia đã rách mất. Dấu X ở phía thác.",
    opts: [
      { t: "Đi tìm kho báu ngay.", s: "khoi_xuong" },
      { t: "Cất đi, đi tiếp việc của mình.", s: "kien_tao" },
      { t: "Ghép với địa hình xem X ở đâu.", s: "dan_duong" },
      { t: "Mơ mộng giàu to cả buổi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt019",
    title: "Bầy khỉ nghịch",
    sit: "Bầy khỉ cướp mất túi lương khô rồi chuyền nhau trên cây, chí chóe trêu bạn.",
    opts: [
      { t: "Trèo lên giành lại luôn.", s: "khoi_xuong" },
      { t: "Bỏ túi đó, chia khẩu phần còn lại.", s: "kien_tao" },
      { t: "Dụ chúng bằng quả rừng để đổi.", s: "dan_duong" },
      { t: "Tức mà buồn cười, đành chịu.", s: "tam_guong" },
    ],
  },
  {
    id: "lt020",
    title: "Giếng cổ",
    sit: "Giếng đá cổ giữa rừng, nước trong veo. Thả đá xuống mãi mới nghe tiếng “tõm”.",
    opts: [
      { t: "Múc uống luôn, khát quá rồi.", s: "khoi_xuong" },
      { t: "Không uống nước lạ trong rừng.", s: "kien_tao" },
      { t: "Ngửi và quan sát trước khi uống.", s: "dan_duong" },
      { t: "Nhìn xuống giếng sâu mà rợn người.", s: "tam_guong" },
    ],
  },
  {
    id: "lt021",
    title: "Trăng máu",
    sit: "Trăng lên đỏ như máu, thú rừng tru vang khắp nơi. Bạn đang ở bãi đất trống.",
    opts: [
      { t: "Đốt lửa to lên, có gì tính sau.", s: "khoi_xuong" },
      { t: "Tìm chỗ trú kín đáo ngay.", s: "kien_tao" },
      { t: "Quan sát xem thú tru vì trăng hay vì khác.", s: "dan_duong" },
      { t: "Sợ đến mức không dám nhúc nhích.", s: "tam_guong" },
    ],
  },
  {
    id: "lt022",
    title: "Người lạ bị thương",
    sit: "Thợ săn lạ bị thương ở chân, xin bạn cõng về làng. Làng ngược hướng bạn đi.",
    opts: [
      { t: "Cõng luôn, cứu người là trên hết.", s: "khoi_xuong" },
      { t: "Băng bó cho họ rồi đi tiếp việc mình.", s: "kien_tao" },
      { t: "Hỏi xem họ bị thương thế nào trước.", s: "dan_duong" },
      { t: "Thương mà sợ trễ việc của mình.", s: "tam_guong" },
    ],
  },
  {
    id: "lt023",
    title: "Hoa phát sáng",
    sit: "Bông hoa xanh phát sáng trong đêm, đẹp mê hoặc. Chạm vào có thể héo ngay.",
    opts: [
      { t: "Hái luôn mang về.", s: "khoi_xuong" },
      { t: "Để yên cho rừng, ngắm là đủ.", s: "kien_tao" },
      { t: "Quan sát xem quanh nó có gì lạ.", s: "dan_duong" },
      { t: "Ngẩn ngơ ngắm mãi không muốn đi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt024",
    title: "Sấm sét",
    sit: "Cơn giông ập đến, sét đánh gần. Bạn đang ở sườn đồi trọc.",
    opts: [
      { t: "Chạy ngay xuống chỗ trũng.", s: "khoi_xuong" },
      { t: "Ngồi xổm, bịt tai, chờ qua cơn.", s: "kien_tao" },
      { t: "Tìm hang đá trú gần nhất.", s: "dan_duong" },
      { t: "Hoảng loạn, chạy lung tung.", s: "tam_guong" },
    ],
  },
  {
    id: "lt025",
    title: "Dấu chân lạ",
    sit: "Dấu chân to gấp ba chân người in trên bùn, còn rất mới. Hướng vào rừng sâu.",
    opts: [
      { t: "Lần theo dấu xem là con gì.", s: "khoi_xuong" },
      { t: "Tránh xa, đi đường khác.", s: "kien_tao" },
      { t: "Đo và quan sát dấu chân kỹ.", s: "dan_duong" },
      { t: "Rợn tóc gáy, muốn quay về.", s: "tam_guong" },
    ],
  },
  {
    id: "lt026",
    title: "Tổ chim non",
    sit: "Tổ chim non rơi xuống đất, chim mẹ kêu quanh quẩn. Tổ còn nguyên.",
    opts: [
      { t: "Trèo lên đặt tổ về chỗ cũ ngay.", s: "khoi_xuong" },
      { t: "Đặt tổ lên bụi thấp gần đó cho an toàn.", s: "kien_tao" },
      { t: "Quan sát xem chim mẹ có tự xử lý không.", s: "dan_duong" },
      { t: "Thương đến rơi nước mắt.", s: "tam_guong" },
    ],
  },
  {
    id: "lt027",
    title: "Mê cung đá",
    sit: "Bãi đá xếp như mê cung, đi 1 tiếng vẫn quay về chỗ cũ. Trời sắp tối.",
    opts: [
      { t: "Đánh dấu đường rồi đi tiếp.", s: "khoi_xuong" },
      { t: "Dừng lại cắm trại, sáng tính.", s: "kien_tao" },
      { t: "Trèo lên cao nhìn toàn cảnh.", s: "dan_duong" },
      { t: "Hoảng vì sợ kẹt lại qua đêm.", s: "tam_guong" },
    ],
  },
  {
    id: "lt028",
    title: "Suối nước nóng",
    sit: "Suối nước nóng bốc hơi nghi ngút sau ngày dài mệt mỏi. Quanh vắng tanh.",
    opts: [
      { t: "Nhảy xuống tắm luôn.", s: "khoi_xuong" },
      { t: "Rửa mặt tay chân cho tỉnh rồi đi.", s: "kien_tao" },
      { t: "Thử nhiệt độ trước đã.", s: "dan_duong" },
      { t: "Ngâm mình mà đầu óc lan man.", s: "tam_guong" },
    ],
  },
  {
    id: "lt029",
    title: "Bóng người trên vách đá",
    sit: "Hoàng hôn in bóng người khổng lồ lên vách đá. Nhìn kỹ thì chỉ có mình bạn.",
    opts: [
      { t: "Tiến lại gần xem là gì.", s: "khoi_xuong" },
      { t: "Kệ, bóng nắng thôi mà.", s: "kien_tao" },
      { t: "Quan sát xem bóng hình thành thế nào.", s: "dan_duong" },
      { t: "Giật mình, tim đập thình thịch.", s: "tam_guong" },
    ],
  },
  {
    id: "lt030",
    title: "Lời nguyền",
    sit: "Phù thủy bảo: muốn qua rừng phải bỏ lại một thứ quý nhất. Bạn mang theo nhẫn cưới mẹ trao.",
    opts: [
      { t: "Đưa luôn, qua được mới quan trọng.", s: "khoi_xuong" },
      { t: "Không đưa, tìm đường khác.", s: "kien_tao" },
      { t: "Hỏi có thứ khác thay thế được không.", s: "dan_duong" },
      { t: "Rơi nước mắt, không nỡ rời chiếc nhẫn.", s: "tam_guong" },
    ],
  },
  {
    id: "lt031",
    title: "Chim đại bàng",
    sit: "Đại bàng sà xuống gắp mất mũ của bạn rồi đậu trên cành cao nhìn xuống.",
    opts: [
      { t: "Trèo lên lấy lại luôn.", s: "khoi_xuong" },
      { t: "Bỏ mũ, đi tiếp cho nhanh.", s: "kien_tao" },
      { t: "Dụ nó bằng thức ăn để đổi.", s: "dan_duong" },
      { t: "Tức mà đành chịu thua con chim.", s: "tam_guong" },
    ],
  },
  {
    id: "lt032",
    title: "Đầm lầy",
    sit: "Đường tắt xuyên đầm lầy đầy hơi độc. Đi vòng mất thêm nửa ngày.",
    opts: [
      { t: "Bịt khăn chạy qua cho nhanh.", s: "khoi_xuong" },
      { t: "Đi vòng, an toàn là trên hết.", s: "kien_tao" },
      { t: "Tìm cành dài dò đường trước.", s: "dan_duong" },
      { t: "Nhìn đầm đen ngòm đã thấy sợ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt033",
    title: "Tiếng sáo",
    sit: "Tiếng sáo du dương từ sâu trong rừng, lúc gần lúc xa. Trời đã nhá nhem.",
    opts: [
      { t: "Đi theo tiếng sáo xem ai thổi.", s: "khoi_xuong" },
      { t: "Mặc kệ, lo chỗ ngủ đêm nay.", s: "kien_tao" },
      { t: "Đứng nghe xem giai điệu quen không.", s: "dan_duong" },
      { t: "Nghe mà buồn man mác, nhớ nhà.", s: "tam_guong" },
    ],
  },
  {
    id: "lt034",
    title: "Hổ vằn",
    sit: "Hổ vằn nằm chắn ngang đường mòn duy nhất, mắt lim dim. Nó chưa thấy bạn.",
    opts: [
      { t: "Ném đá đánh lạc hướng rồi chạy qua.", s: "khoi_xuong" },
      { t: "Rút lui thật khẽ, chờ nó đi.", s: "kien_tao" },
      { t: "Quan sát xem nó ngủ thật hay giả.", s: "dan_duong" },
      { t: "Nín thở, tim như muốn nhảy ra ngoài.", s: "tam_guong" },
    ],
  },
  {
    id: "lt035",
    title: "Cây cầu khỉ",
    sit: "Cầu khỉ lắc lư qua sông, dưới là nước xiết. Người gùi nặng đi trước vừa qua an toàn.",
    opts: [
      { t: "Đi qua luôn, người ta qua được mình qua được.", s: "khoi_xuong" },
      { t: "Bám chắc, đi chậm từng bước.", s: "kien_tao" },
      { t: "Hỏi người vừa qua xem có đoạn nào yếu.", s: "dan_duong" },
      { t: "Nhìn nước xiết đã thấy chóng mặt.", s: "tam_guong" },
    ],
  },
  {
    id: "lt036",
    title: "Kho báu rồng",
    sit: "Hang rồng đầy vàng, rồng đang ngủ say. Lấy một ít là đủ giàu cả đời.",
    opts: [
      { t: "Vơ một nắm rồi chuồn nhanh.", s: "khoi_xuong" },
      { t: "Không động vào, rút lui lặng lẽ.", s: "kien_tao" },
      { t: "Quan sát xem rồng ngủ say cỡ nào.", s: "dan_duong" },
      { t: "Thèm mà sợ, tim đập loạn xạ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt037",
    title: "Cơn lũ quét",
    sit: "Nước lũ từ thượng nguồn đổ về ầm ầm. Bạn đang ở bãi đất thấp.",
    opts: [
      { t: "Chạy ngay lên chỗ cao nhất gần đó.", s: "khoi_xuong" },
      { t: "Trèo lên cây to chắc chắn nhất.", s: "kien_tao" },
      { t: "Nhìn dòng nước đoán hướng an toàn.", s: "dan_duong" },
      { t: "Hoảng loạn, không biết chạy đâu.", s: "tam_guong" },
    ],
  },
  {
    id: "lt038",
    title: "Người rừng",
    sit: "Người rừng xuất hiện, ra hiệu đi theo. Ngôn ngữ bất đồng, ánh mắt thì hiền.",
    opts: [
      { t: "Đi theo luôn, có gì tính sau.", s: "khoi_xuong" },
      { t: "Lắc đầu, đi đường của mình.", s: "kien_tao" },
      { t: "Quan sát thêm rồi mới quyết.", s: "dan_duong" },
      { t: "Sợ mà tò mò, đứng chôn chân.", s: "tam_guong" },
    ],
  },
  {
    id: "lt039",
    title: "Nấm phát sáng",
    sit: "Vạt nấm xanh phát sáng rực cả góc rừng đêm. Đẹp như trong truyện cổ tích.",
    opts: [
      { t: "Hái một ít mang về nghiên cứu.", s: "khoi_xuong" },
      { t: "Chụp ảnh (trong đầu) rồi đi tiếp.", s: "kien_tao" },
      { t: "Quan sát xem có con gì ăn nó không.", s: "dan_duong" },
      { t: "Đứng ngắm mãi quên cả thời gian.", s: "tam_guong" },
    ],
  },
  {
    id: "lt040",
    title: "Chia lương thực",
    sit: "Lương thực chỉ còn đủ 2 ngày mà đường còn 4 ngày. Bạn đi cùng 1 người lạ.",
    opts: [
      { t: "Chia đôi sòng phẳng, cùng gánh.", s: "khoi_xuong" },
      { t: "Ăn dè từng bữa cho đủ đường.", s: "kien_tao" },
      { t: "Bàn với họ kế hoạch kiếm thêm thức ăn.", s: "dan_duong" },
      { t: "Lo lắng, nhường phần hơn cho họ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt041",
    title: "Vết thương",
    sit: "Bạn bị cành cây cứa rách tay, máu chảy khá nhiều. Không có thuốc.",
    opts: [
      { t: "Xé áo buộc chặt rồi đi tiếp.", s: "khoi_xuong" },
      { t: "Rửa sạch, băng kỹ, nghỉ một lúc.", s: "kien_tao" },
      { t: "Tìm lá thuốc trong rừng đắp tạm.", s: "dan_duong" },
      { t: "Nhìn máu đã thấy choáng.", s: "tam_guong" },
    ],
  },
  {
    id: "lt042",
    title: "Hai con đường",
    sit: "Đường bằng phẳng nhưng xa, đường tắt dốc đứng đầy đá. Trời sắp tối.",
    opts: [
      { t: "Đi tắt cho kịp trước tối.", s: "khoi_xuong" },
      { t: "Đi đường bằng, tối thì cắm trại.", s: "kien_tao" },
      { t: "Leo thử một đoạn xem dốc cỡ nào.", s: "dan_duong" },
      { t: "Phân vân mãi đến khi trời tối hẳn.", s: "tam_guong" },
    ],
  },
  {
    id: "lt043",
    title: "Ong vỡ tổ",
    sit: "Bạn vô tình động vào tổ ong, cả đàn ùa ra vo ve. Gần đó có suối.",
    opts: [
      { t: "Nhảy xuống suối ngay.", s: "khoi_xuong" },
      { t: "Trùm áo kín đầu, đi chậm ra xa.", s: "kien_tao" },
      { t: "Nằm yên chờ ong bay đi.", s: "dan_duong" },
      { t: "Vừa chạy vừa la hét hoảng loạn.", s: "tam_guong" },
    ],
  },
  {
    id: "lt044",
    title: "Tượng đá cổ",
    sit: "Tượng đá nghìn năm khắc chữ lạ, tay chỉ về phía vực. Rêu phủ kín.",
    opts: [
      { t: "Đi theo hướng tay chỉ xem sao.", s: "khoi_xuong" },
      { t: "Ghi nhớ vị trí, đi đường mình.", s: "kien_tao" },
      { t: "Cố đọc chữ khắc trên tượng.", s: "dan_duong" },
      { t: "Thấy linh thiêng, không dám động vào.", s: "tam_guong" },
    ],
  },
  {
    id: "lt045",
    title: "Mưa đá",
    sit: "Mưa đá bất ngờ đổ xuống, viên to bằng ngón tay. Quanh không có chỗ trú.",
    opts: [
      { t: "Chạy hết sức tìm chỗ trú.", s: "khoi_xuong" },
      { t: "Lấy balo che đầu, cúi người chịu trận.", s: "kien_tao" },
      { t: "Tìm gốc cây to trú tạm.", s: "dan_duong" },
      { t: "Hoảng, chỉ biết ôm đầu.", s: "tam_guong" },
    ],
  },
  {
    id: "lt046",
    title: "Chú nai bị thương",
    sit: "Nai con bị thương nằm bên đường, mắt ướt nhìn bạn. Bạn đang vội.",
    opts: [
      { t: "Băng bó nhanh rồi đi tiếp.", s: "khoi_xuong" },
      { t: "Ở lại chăm đến khi nó đứng được.", s: "kien_tao" },
      { t: "Xem vết thương nặng nhẹ thế nào.", s: "dan_duong" },
      { t: "Thương quá, không nỡ bỏ đi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt047",
    title: "Đêm không lửa",
    sit: "Củi ướt hết, không nhóm được lửa. Đêm rừng lạnh buốt, thú kêu quanh.",
    opts: [
      { t: "Đi tiếp trong đêm cho ấm người.", s: "khoi_xuong" },
      { t: "Cuộn tròn trong túi ngủ chịu lạnh.", s: "kien_tao" },
      { t: "Tìm củi khô dưới gốc cây to.", s: "dan_duong" },
      { t: "Run cầm cập vì lạnh và sợ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt048",
    title: "Cây đổ chắn suối",
    sit: "Thân cây đổ chắn ngang suối, tạo thành cầu tự nhiên nhưng trơn rêu.",
    opts: [
      { t: "Đi qua luôn, cẩn thận là được.", s: "khoi_xuong" },
      { t: "Lội suối cho chắc ăn.", s: "kien_tao" },
      { t: "Thử độ chắc của thân cây trước.", s: "dan_duong" },
      { t: "Nhìn rêu trơn đã thấy sợ ngã.", s: "tam_guong" },
    ],
  },
  {
    id: "lt049",
    title: "Tiếng cười trong rừng",
    sit: "Tiếng cười trẻ con vang lên giữa rừng hoang, không thấy ai. Lúc gần lúc xa.",
    opts: [
      { t: "Đi tìm xem ai đang đùa.", s: "khoi_xuong" },
      { t: "Mặc kệ, đi tiếp đường mình.", s: "kien_tao" },
      { t: "Đứng nghe xem tiếng từ đâu.", s: "dan_duong" },
      { t: "Sởn da gà, bước nhanh hơn.", s: "tam_guong" },
    ],
  },
  {
    id: "lt050",
    title: "Quả dại",
    sit: "Bụi quả dại chín mọng, chim ăn bình thường. Bụng bạn đói meo.",
    opts: [
      { t: "Ăn luôn, chim ăn được mình ăn được.", s: "khoi_xuong" },
      { t: "Không ăn quả lạ trong rừng.", s: "kien_tao" },
      { t: "Ăn thử một quả, chờ xem sao.", s: "dan_duong" },
      { t: "Đói mà sợ độc, đành nhịn.", s: "tam_guong" },
    ],
  },
  {
    id: "lt051",
    title: "Bình minh trên đỉnh",
    sit: "Sau đêm leo núi, bình minh rực rỡ trước mặt. Cảnh đẹp đến nghẹt thở.",
    opts: [
      { t: "Hét to một tiếng cho đã.", s: "khoi_xuong" },
      { t: "Ngồi lặng ngắm cho đã mắt.", s: "kien_tao" },
      { t: "Quan sát đường đi tiếp từ trên cao.", s: "dan_duong" },
      { t: "Xúc động đến rưng rưng.", s: "tam_guong" },
    ],
  },
  {
    id: "lt052",
    title: "Lạc đường",
    sit: "Bạn nhận ra mình đi vòng 2 tiếng vẫn một chỗ. La bàn quay tít.",
    opts: [
      { t: "Chọn một hướng đi thẳng không quay đầu.", s: "khoi_xuong" },
      { t: "Dừng lại, đánh dấu, nghỉ lấy sức.", s: "kien_tao" },
      { t: "Trèo cây cao xác định phương hướng.", s: "dan_duong" },
      { t: "Hoảng vì sợ không ra được.", s: "tam_guong" },
    ],
  },
  {
    id: "lt053",
    title: "Cá vàng",
    sit: "Suối có con cá vàng óng ánh, bắt được nghe nói may mắn cả năm.",
    opts: [
      { t: "Lao xuống bắt ngay.", s: "khoi_xuong" },
      { t: "Để nó sống, may mắn tự đến.", s: "kien_tao" },
      { t: "Quan sát xem nó bơi về đâu.", s: "dan_duong" },
      { t: "Ngắm mãi không nỡ bắt.", s: "tam_guong" },
    ],
  },
  {
    id: "lt054",
    title: "Đêm trăng tròn",
    sit: "Trăng tròn vành vạnh, rừng sáng như ban ngày. Bạn không buồn ngủ.",
    opts: [
      { t: "Đi tiếp luôn, trăng sáng thế này.", s: "khoi_xuong" },
      { t: "Ngủ sớm lấy sức mai đi.", s: "kien_tao" },
      { t: "Ngồi ngắm trăng một lúc rồi ngủ.", s: "dan_duong" },
      { t: "Nằm nhớ nhà, nhớ người thương.", s: "tam_guong" },
    ],
  },
  {
    id: "lt055",
    title: "Tiếng gầm xa",
    sit: "Tiếng gầm lớn từ thung lũng vọng lên. Mặt đất rung nhẹ.",
    opts: [
      { t: "Tiến lại gần xem là gì.", s: "khoi_xuong" },
      { t: "Rời xa ngay lập tức.", s: "kien_tao" },
      { t: "Lắng nghe xem còn gầm nữa không.", s: "dan_duong" },
      { t: "Tim đập loạn, muốn chạy ngay.", s: "tam_guong" },
    ],
  },
  {
    id: "lt056",
    title: "Cầu vồng sau mưa",
    sit: "Mưa tạnh, cầu vồng rực rỡ bắc qua thung lũng. Chân cầu vồng ở gần bạn.",
    opts: [
      { t: "Chạy đến chân cầu vồng xem.", s: "khoi_xuong" },
      { t: "Đứng ngắm, đẹp là đủ.", s: "kien_tao" },
      { t: "Đoán xem mưa có quay lại không.", s: "dan_duong" },
      { t: "Thấy lòng nhẹ nhõm lạ thường.", s: "tam_guong" },
    ],
  },
  {
    id: "lt057",
    title: "Bẫy thợ săn",
    sit: "Bạn sập bẫy kẹp, chân đau điếng. Quanh không một bóng người.",
    opts: [
      { t: "Gỡ bẫy ngay dù đau.", s: "khoi_xuong" },
      { t: "Bình tĩnh gỡ từng chút một.", s: "kien_tao" },
      { t: "Xem cấu tạo bẫy rồi gỡ cho đúng.", s: "dan_duong" },
      { t: "Hoảng và đau đến phát khóc.", s: "tam_guong" },
    ],
  },
  {
    id: "lt058",
    title: "Làng trong rừng",
    sit: "Làng nhỏ hiện ra giữa rừng, khói bếp bay lên. Người làng nhìn bạn lạ lẫm.",
    opts: [
      { t: "Tiến vào chào hỏi ngay.", s: "khoi_xuong" },
      { t: "Đi vòng tránh, không muốn phiền.", s: "kien_tao" },
      { t: "Quan sát từ xa trước đã.", s: "dan_duong" },
      { t: "Ngại vì thấy mình là người lạ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt059",
    title: "Cơn khát",
    sit: "Hết nước từ sáng, cổ họng khô rát. Phía trước có vũng nước đọng đục ngầu.",
    opts: [
      { t: "Uống luôn, khát quá rồi.", s: "khoi_xuong" },
      { t: "Nhịn tiếp, tìm nguồn sạch hơn.", s: "kien_tao" },
      { t: "Lọc qua khăn rồi mới uống.", s: "dan_duong" },
      { t: "Khát mà sợ đau bụng.", s: "tam_guong" },
    ],
  },
  {
    id: "lt060",
    title: "Trận chiến của bầy",
    sit: "Hai bầy thú đánh nhau tranh lãnh địa ngay trên đường bạn đi.",
    opts: [
      { t: "Chạy xuyên qua lúc chúng mải đánh.", s: "khoi_xuong" },
      { t: "Đi vòng xa, chờ chúng xong.", s: "kien_tao" },
      { t: "Trèo cây quan sát rồi tính.", s: "dan_duong" },
      { t: "Sợ đến mức không dám thở mạnh.", s: "tam_guong" },
    ],
  },
  {
    id: "lt061",
    title: "Hạt giống lạ",
    sit: "Cụ già trong làng tặng hạt giống lạ, bảo: “Trồng ở nơi con thuộc về.”",
    opts: [
      { t: "Trồng ngay ở đây luôn.", s: "khoi_xuong" },
      { t: "Cất kỹ, về nhà mới trồng.", s: "kien_tao" },
      { t: "Hỏi cụ đây là hạt gì.", s: "dan_duong" },
      { t: "Cầm hạt mà bâng khuâng.", s: "tam_guong" },
    ],
  },
  {
    id: "lt062",
    title: "Sương muối",
    sit: "Sáng sớm sương muối phủ trắng, đường trơn như đổ mỡ. Bạn phải xuống núi hôm nay.",
    opts: [
      { t: "Đi luôn, cẩn thận từng bước.", s: "khoi_xuong" },
      { t: "Chờ nắng lên tan sương rồi đi.", s: "kien_tao" },
      { t: "Tìm gậy chống rồi mới đi.", s: "dan_duong" },
      { t: "Sợ ngã nên chần chừ mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt063",
    title: "Tiếng chuông chùa",
    sit: "Tiếng chuông chùa từ đâu vọng đến, trầm và xa. Bạn đã đi nhiều ngày.",
    opts: [
      { t: "Lần theo tiếng chuông tìm chùa.", s: "khoi_xuong" },
      { t: "Đi tiếp đường mình, chuông kệ chuông.", s: "kien_tao" },
      { t: "Dừng nghe xem chuông từ hướng nào.", s: "dan_duong" },
      { t: "Nghe chuông mà lòng chùng xuống.", s: "tam_guong" },
    ],
  },
  {
    id: "lt064",
    title: "Vách đá dựng đứng",
    sit: "Vách đá dựng đứng chắn đường, có dây leo nhưng không biết chắc không.",
    opts: [
      { t: "Leo luôn, tin vào tay mình.", s: "khoi_xuong" },
      { t: "Tìm đường vòng dù xa.", s: "kien_tao" },
      { t: "Giật thử dây leo trước.", s: "dan_duong" },
      { t: "Nhìn lên đỉnh đã thấy nản.", s: "tam_guong" },
    ],
  },
  {
    id: "lt065",
    title: "Bữa tiệc của rừng",
    sit: "Thú rừng tụ họp quanh đống quả chín như mở tiệc. Chúng không để ý bạn.",
    opts: [
      { t: "Hòa vào luôn, vui cùng chúng.", s: "khoi_xuong" },
      { t: "Đứng xa ngắm, không quấy rầy.", s: "kien_tao" },
      { t: "Quan sát xem con nào là đầu đàn.", s: "dan_duong" },
      { t: "Thấy ấm lòng, quên cả mệt.", s: "tam_guong" },
    ],
  },
  {
    id: "lt066",
    title: "Giấc mơ lạ",
    sit: "Đêm trong rừng bạn mơ thấy mình hóa thành chim bay qua núi. Tỉnh dậy trời chưa sáng.",
    opts: [
      { t: "Dậy đi tiếp luôn, coi như điềm tốt.", s: "khoi_xuong" },
      { t: "Ngủ tiếp, mơ chỉ là mơ.", s: "kien_tao" },
      { t: "Ngẫm xem giấc mơ muốn nói gì.", s: "dan_duong" },
      { t: "Nằm nhớ mãi cảm giác được bay.", s: "tam_guong" },
    ],
  },
  {
    id: "lt067",
    title: "Dòng sông đổi màu",
    sit: "Dòng sông bỗng chuyển màu ngọc bích, cá nhảy tung tăng. Đẹp đến khó tin.",
    opts: [
      { t: "Lội xuống xem nước có gì lạ.", s: "khoi_xuong" },
      { t: "Ngắm rồi đi, không tò mò.", s: "kien_tao" },
      { t: "Tìm hiểu vì sao nước đổi màu.", s: "dan_duong" },
      { t: "Mê mẩn đứng nhìn mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt068",
    title: "Cây cầu mới",
    sit: "Dân làng đang dựng cầu mới, thiếu người phụ. Bạn đang vội về.",
    opts: [
      { t: "Ở lại phụ một tay rồi đi.", s: "khoi_xuong" },
      { t: "Đi tiếp, việc mình còn dang dở.", s: "kien_tao" },
      { t: "Hỏi xem cần giúp bao lâu.", s: "dan_duong" },
      { t: "Muốn giúp mà sợ trễ việc.", s: "tam_guong" },
    ],
  },
  {
    id: "lt069",
    title: "Hòn đá ước",
    sit: "Hòn đá khắc: “Ném xuống hồ sẽ thành ước nguyện.” Hồ sâu thăm thẳm.",
    opts: [
      { t: "Ước rồi ném luôn.", s: "khoi_xuong" },
      { t: "Không tin, đi tiếp.", s: "kien_tao" },
      { t: "Nhìn xem dưới hồ có gì không.", s: "dan_duong" },
      { t: "Cầm đá mà không biết ước gì.", s: "tam_guong" },
    ],
  },
  {
    id: "lt070",
    title: "Bão cát",
    sit: "Bão cát từ thung lũng kéo đến, trời vàng khè. Bạn còn cách làng 1 giờ đi.",
    opts: [
      { t: "Chạy hết sức về làng.", s: "khoi_xuong" },
      { t: "Tìm chỗ trú, chờ bão qua.", s: "kien_tao" },
      { t: "Xem hướng gió rồi tính.", s: "dan_duong" },
      { t: "Hoảng, không biết làm gì.", s: "tam_guong" },
    ],
  },
  {
    id: "lt071",
    title: "Con đường hoa",
    sit: "Con đường rải đầy hoa dại thơm ngát, bướm bay rợp trời. Đẹp như mơ.",
    opts: [
      { t: "Chạy ào qua, tận hưởng luôn.", s: "khoi_xuong" },
      { t: "Đi chậm rãi, hít hà hương hoa.", s: "kien_tao" },
      { t: "Ngắm xem có hoa lạ nào không.", s: "dan_duong" },
      { t: "Đứng lặng vì đẹp quá.", s: "tam_guong" },
    ],
  },
  {
    id: "lt072",
    title: "Hang dơi",
    sit: "Phải qua hang dơi lúc chạng vạng, đúng giờ chúng bay ra. Tiếng kêu rợn người.",
    opts: [
      { t: "Đi xuyên qua luôn cho nhanh.", s: "khoi_xuong" },
      { t: "Chờ chúng bay hết rồi mới qua.", s: "kien_tao" },
      { t: "Tìm lối khác tránh hang.", s: "dan_duong" },
      { t: "Sợ đến mức không dám vào.", s: "tam_guong" },
    ],
  },
  {
    id: "lt073",
    title: "Lửa rừng",
    sit: "Khói bốc lên ở sườn bên, lửa đang lan. Gió thổi về phía bạn.",
    opts: [
      { t: "Chạy ngược gió ngay lập tức.", s: "khoi_xuong" },
      { t: "Tìm suối hoặc bãi đất trống trú.", s: "kien_tao" },
      { t: "Xem lửa lan nhanh cỡ nào rồi tính.", s: "dan_duong" },
      { t: "Hoảng loạn, chạy lung tung.", s: "tam_guong" },
    ],
  },
  {
    id: "lt074",
    title: "Cái giếng ước",
    sit: "Giếng cổ khắc: “Thả một đồng xu, nói một điều ước.” Bạn còn đúng một đồng.",
    opts: [
      { t: "Thả luôn, tin thì ước.", s: "khoi_xuong" },
      { t: "Giữ đồng xu, ước bằng hành động.", s: "kien_tao" },
      { t: "Nhìn xuống giếng trước đã.", s: "dan_duong" },
      { t: "Cầm xu phân vân mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt075",
    title: "Đàn voi",
    sit: "Đàn voi 10 con băng qua đường bạn đi, con nào cũng to như xe tải.",
    opts: [
      { t: "Đi theo sau đàn xem chúng đi đâu.", s: "khoi_xuong" },
      { t: "Đứng yên chờ chúng qua hết.", s: "kien_tao" },
      { t: "Quan sát con đầu đàn.", s: "dan_duong" },
      { t: "Nép sát gốc cây vì sợ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt076",
    title: "Mưa sao băng",
    sit: "Đêm nay mưa sao băng rực trời. Bạn đang ở đỉnh đồi quang đãng.",
    opts: [
      { t: "Ước thật nhiều điều luôn.", s: "khoi_xuong" },
      { t: "Nằm ngắm trong yên lặng.", s: "kien_tao" },
      { t: "Đếm xem có bao nhiêu vệt.", s: "dan_duong" },
      { t: "Ngắm mà thấy mình nhỏ bé.", s: "tam_guong" },
    ],
  },
  {
    id: "lt077",
    title: "Cây khô giữa rừng xanh",
    sit: "Một cây khô trơ trụi đứng giữa rừng xanh mướt. Lạ lùng và cô độc.",
    opts: [
      { t: "Lại gần xem có gì đặc biệt.", s: "khoi_xuong" },
      { t: "Đi qua, cây nào chẳng có số.", s: "kien_tao" },
      { t: "Ngẫm xem sao nó chết khô.", s: "dan_duong" },
      { t: "Thấy thương cây, buồn man mác.", s: "tam_guong" },
    ],
  },
  {
    id: "lt078",
    title: "Suối cạn",
    sit: "Con suối trên bản đồ đã cạn trơ đá. Bạn đang khát và cần nước.",
    opts: [
      { t: "Đi tiếp tìm nguồn khác ngay.", s: "khoi_xuong" },
      { t: "Đào cát lòng suối tìm mạch nước.", s: "kien_tao" },
      { t: "Lần ngược lên thượng nguồn.", s: "dan_duong" },
      { t: "Thất vọng ngồi bệt xuống.", s: "tam_guong" },
    ],
  },
  {
    id: "lt079",
    title: "Bóng trăng đáy nước",
    sit: "Trăng in đáy suối trong veo, đẹp đến mức bạn không nỡ khuấy động.",
    opts: [
      { t: "Chạm tay xuống xem sao.", s: "khoi_xuong" },
      { t: "Ngồi ngắm một lúc rồi đi.", s: "kien_tao" },
      { t: "Tìm chỗ ngắm đẹp nhất.", s: "dan_duong" },
      { t: "Ngắm mãi quên cả thời gian.", s: "tam_guong" },
    ],
  },
  {
    id: "lt080",
    title: "Lối ra",
    sit: "Sau 7 ngày, cuối cùng bạn thấy ánh sáng cuối đường hầm. Rừng sắp hết.",
    opts: [
      { t: "Chạy ào ra luôn.", s: "khoi_xuong" },
      { t: "Đi chậm, ngoảnh nhìn rừng lần cuối.", s: "kien_tao" },
      { t: "Quan sát xem bên ngoài là đâu.", s: "dan_duong" },
      { t: "Vừa mừng vừa tiếc, không muốn ra.", s: "tam_guong" },
    ],
  },
  {
    id: "lt081",
    title: "Quà của rừng",
    sit: "Trước khi ra, bạn thấy túi thơm ai để lại kèm giấy: “Quà cho kẻ kiên nhẫn.”",
    opts: [
      { t: "Mở ra xem là gì.", s: "khoi_xuong" },
      { t: "Mang về, để dành tặng người thương.", s: "kien_tao" },
      { t: "Ngửi thử xem thơm mùi gì.", s: "dan_duong" },
      { t: "Cầm quà mà rưng rưng.", s: "tam_guong" },
    ],
  },
  {
    id: "lt082",
    title: "Con thuyền không người",
    sit: "Thuyền nan trôi trên hồ, không người lái. Bên trong có ngọn đèn còn sáng.",
    opts: [
      { t: "Nhảy lên thuyền xem đi đâu.", s: "khoi_xuong" },
      { t: "Kệ, đi đường bộ của mình.", s: "kien_tao" },
      { t: "Gọi to xem có ai quanh đó không.", s: "dan_duong" },
      { t: "Thấy huyền hoặc, hơi sợ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt083",
    title: "Rễ cây khổng lồ",
    sit: "Rễ cây to như con trăn chắn đường, muốn qua phải chui hoặc trèo.",
    opts: [
      { t: "Trèo qua luôn.", s: "khoi_xuong" },
      { t: "Chui chậm rãi cho an toàn.", s: "kien_tao" },
      { t: "Đi dọc rễ tìm chỗ thấp nhất.", s: "dan_duong" },
      { t: "Nhìn rễ ngoằn ngoèo đã thấy ngại.", s: "tam_guong" },
    ],
  },
  {
    id: "lt084",
    title: "Đàn cá bay",
    sit: "Đàn cá bạc bay khỏi mặt hồ lấp lánh dưới nắng. Chưa bao giờ bạn thấy thế.",
    opts: [
      { t: "Lội xuống bắt thử một con.", s: "khoi_xuong" },
      { t: "Ngồi ngắm cho thỏa.", s: "kien_tao" },
      { t: "Quan sát xem chúng bay về đâu.", s: "dan_duong" },
      { t: "Ngẩn ngơ vì đẹp quá.", s: "tam_guong" },
    ],
  },
  {
    id: "lt085",
    title: "Hang gió",
    sit: "Hang thổi gió mát rượi, tiếng gió như ai đang hát. Ngoài trời nóng hầm hập.",
    opts: [
      { t: "Vào trong tránh nóng luôn.", s: "khoi_xuong" },
      { t: "Nghỉ ở cửa hang cho an toàn.", s: "kien_tao" },
      { t: "Nghe xem tiếng hát từ đâu.", s: "dan_duong" },
      { t: "Vừa mát vừa rợn, không dám vào sâu.", s: "tam_guong" },
    ],
  },
  {
    id: "lt086",
    title: "Bầy bướm",
    sit: "Hàng nghìn con bướm bay qua tạo thành dải lụa đủ màu. Bạn đứng giữa đường bay.",
    opts: [
      { t: "Chạy theo đàn bướm.", s: "khoi_xuong" },
      { t: "Đứng yên cho chúng bay qua.", s: "kien_tao" },
      { t: "Nhìn xem chúng bay về hướng nào.", s: "dan_duong" },
      { t: "Xúc động đến quên cả chớp mắt.", s: "tam_guong" },
    ],
  },
  {
    id: "lt087",
    title: "Cây nấm khổng lồ",
    sit: "Cây nấm to như cái ô che cả khoảng đất. Dưới nấm khô ráo, ngoài trời đang mưa.",
    opts: [
      { t: "Chui vào trú mưa luôn.", s: "khoi_xuong" },
      { t: "Mặc áo mưa đi tiếp.", s: "kien_tao" },
      { t: "Xem nấm có độc không trước.", s: "dan_duong" },
      { t: "Thích thú ngắm mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "lt088",
    title: "Vết chân chim",
    sit: "Vết chân chim khổng lồ in trên cát, mỗi bước cách nhau 5 mét.",
    opts: [
      { t: "Lần theo xem chim gì to thế.", s: "khoi_xuong" },
      { t: "Tránh xa, không dây vào.", s: "kien_tao" },
      { t: "Đo đạc, đoán xem nó to cỡ nào.", s: "dan_duong" },
      { t: "Tưởng tượng con chim mà rợn người.", s: "tam_guong" },
    ],
  },
  {
    id: "lt089",
    title: "Suối đá cuội",
    sit: "Suối cạn lộ bãi đá cuội đủ màu, tròn nhẵn. Đẹp như tranh.",
    opts: [
      { t: "Nhặt vài viên đẹp mang về.", s: "khoi_xuong" },
      { t: "Ngắm rồi đi, để nguyên cho rừng.", s: "kien_tao" },
      { t: "Tìm viên lạ nhất trong bãi.", s: "dan_duong" },
      { t: "Ngồi nghịch đá quên giờ giấc.", s: "tam_guong" },
    ],
  },
  {
    id: "lt090",
    title: "Tiếng chuông gió",
    sit: "Chuông gió treo trên cành cao kêu leng keng dù không có gió.",
    opts: [
      { t: "Trèo lên xem ai treo.", s: "khoi_xuong" },
      { t: "Đi tiếp, chuông của rừng.", s: "kien_tao" },
      { t: "Đứng nghe xem kêu theo nhịp gì.", s: "dan_duong" },
      { t: "Nghe mà gai người.", s: "tam_guong" },
    ],
  },
  {
    id: "lt091",
    title: "Đồi cỏ lau",
    sit: "Đồi cỏ lau trắng xóa đung đưa trong gió chiều. Hoàng hôn buông.",
    opts: [
      { t: "Chạy lên đỉnh đồi ngắm hoàng hôn.", s: "khoi_xuong" },
      { t: "Ngồi lại nghỉ, ngắm từ đây.", s: "kien_tao" },
      { t: "Tìm chỗ ngắm đẹp nhất.", s: "dan_duong" },
      { t: "Thấy lòng bình yên lạ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt092",
    title: "Con đường mòn mới",
    sit: "Đường mòn rẽ hai: lối cũ quen thuộc và lối mới đầy hoa dại.",
    opts: [
      { t: "Đi lối mới, biết đâu có bất ngờ.", s: "khoi_xuong" },
      { t: "Đi lối cũ cho chắc.", s: "kien_tao" },
      { t: "Thử lối mới một đoạn xem sao.", s: "dan_duong" },
      { t: "Phân vân đứng mãi ở ngã rẽ.", s: "tam_guong" },
    ],
  },
  {
    id: "lt093",
    title: "Ánh sáng cuối rừng",
    sit: "Vệt sáng lạ xuyên qua tán lá, chiếu đúng một gốc cây mục.",
    opts: [
      { t: "Lại xem có gì ở đó.", s: "khoi_xuong" },
      { t: "Đi tiếp, nắng xuyên lá thôi.", s: "kien_tao" },
      { t: "Quan sát xem sáng từ đâu tới.", s: "dan_duong" },
      { t: "Thấy như có điềm gì.", s: "tam_guong" },
    ],
  },
  {
    id: "lt094",
    title: "Bầy đom đóm cuối",
    sit: "Đêm cuối trong rừng, đom đóm tụ thành hình trái tim quanh bạn.",
    opts: [
      { t: "Chụp (trong đầu) rồi hét lên vui sướng.", s: "khoi_xuong" },
      { t: "Ngồi yên tận hưởng khoảnh khắc.", s: "kien_tao" },
      { t: "Ngẫm xem rừng muốn nói gì với mình.", s: "dan_duong" },
      { t: "Rưng rưng vì thấy được yêu thương.", s: "tam_guong" },
    ],
  },
  {
    id: "lt095",
    title: "Lời tạm biệt rừng",
    sit: "Sáng ra khỏi rừng, bạn ngoảnh lại. Rừng im lặng như chưa từng có gì.",
    opts: [
      { t: "Hét to: “Cảm ơn, tao sẽ quay lại!”", s: "khoi_xuong" },
      { t: "Cúi chào rồi đi thẳng.", s: "kien_tao" },
      { t: "Đứng ngẫm xem mình học được gì.", s: "dan_duong" },
      { t: "Bịn rịn không muốn rời.", s: "tam_guong" },
    ],
  },
  {
    id: "lt096",
    title: "Món quà cuối",
    sit: "Ở cổng ra, bạn thấy ba lô mình đầy ắp quả rừng. Không biết ai cho.",
    opts: [
      { t: "Ăn luôn một quả xem sao.", s: "khoi_xuong" },
      { t: "Mang về chia cho mọi người.", s: "kien_tao" },
      { t: "Đoán xem ai đã cho mình.", s: "dan_duong" },
      { t: "Cảm động đến nghẹn lời.", s: "tam_guong" },
    ],
  },
  {
    id: "lt097",
    title: "Người đón ở cổng",
    sit: "Người thương đứng chờ ở cổng rừng từ bao giờ, tay cầm áo ấm.",
    opts: [
      { t: "Chạy ào đến ôm chầm.", s: "khoi_xuong" },
      { t: "Mỉm cười bước tới thật chắc.", s: "kien_tao" },
      { t: "Hỏi sao họ biết mình ra hôm nay.", s: "dan_duong" },
      { t: "Khóc òa vì xúc động.", s: "tam_guong" },
    ],
  },
  {
    id: "lt098",
    title: "Kể chuyện rừng",
    sit: "Về làng, ai cũng hỏi trong rừng có gì. Chuyện dài 7 ngày không kể hết.",
    opts: [
      { t: "Kể ngay những pha gay cấn nhất.", s: "khoi_xuong" },
      { t: "Kể từ tốn từ đầu đến cuối.", s: "kien_tao" },
      { t: "Kể những điều mình ngộ ra.", s: "dan_duong" },
      { t: "Kể mà mắt long lanh nhớ rừng.", s: "tam_guong" },
    ],
  },
  {
    id: "lt099",
    title: "Hẹn ngày trở lại",
    sit: "Trước khi đi xa, bạn hứa với lòng sẽ quay lại rừng một ngày nào đó.",
    opts: [
      { t: "Định luôn ngày tháng cụ thể.", s: "khoi_xuong" },
      { t: "Giữ lời hứa trong tim, đủ duyên sẽ về.", s: "kien_tao" },
      { t: "Lên kế hoạch cho chuyến sau tốt hơn.", s: "dan_duong" },
      { t: "Nhớ rừng da diết.", s: "tam_guong" },
    ],
  },
  {
    id: "lt100",
    title: "Linh thú của bạn",
    sit: "Đêm cuối, bạn mơ thấy linh thú của mình hiện ra. Nó không nói gì, chỉ nhìn bạn.",
    opts: [
      { t: "Tiến tới chạm vào nó.", s: "khoi_xuong" },
      { t: "Chắp tay cảm ơn nó.", s: "kien_tao" },
      { t: "Nhìn sâu vào mắt nó để hiểu.", s: "dan_duong" },
      { t: "Khóc vì thấy được thấu hiểu.", s: "tam_guong" },
    ],
  },
];
