import type { BankQuestion } from "./bank";

// Kho 100 câu concept Thương Vụ: sự nghiệp, deal, đội nhóm, tiền bạc.
export const BANK_THUONG_VU: BankQuestion[] = [
  {
    id: "tv001",
    title: "Deal triệu đô",
    sit: "Khách hàng lớn gật đầu miệng nhưng chưa ký. Đối thủ đang lảng vảng quanh họ.",
    opts: [
      { t: "Chốt cọc ngay hôm nay, đêm dài lắm mộng.", s: "khoi_xuong" },
      { t: "Gửi hợp đồng chỉn chu, theo sát từng ngày.", s: "kien_tao" },
      { t: "Tìm hiểu xem họ còn lăn tăn điều gì.", s: "dan_duong" },
      { t: "Lo mất deal đến mất ngủ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv002",
    title: "Nhân viên xin nghỉ",
    sit: "Nhân sự chủ chốt xin nghỉ đúng lúc dự án gấp. Lý do: “chán”.",
    opts: [
      { t: "Giữ chân bằng đề xuất mới ngay hôm nay.", s: "kien_tao" },
      { t: "Ngồi nghe xem họ chán điều gì thật sự.", s: "dan_duong" },
      { t: "Buồn và tự trách mình quản lý kém.", s: "tam_guong" },
      { t: "Để họ đi, tìm người mới máu lửa hơn.", s: "khoi_xuong" },
    ],
  },
  {
    id: "tv003",
    title: "Đối thủ phá giá",
    sit: "Đối thủ giảm giá 30% để cướp khách của bạn. Doanh số tháng này lao dốc.",
    opts: [
      { t: "Giảm giá sâu hơn, chơi tới cùng.", s: "khoi_xuong" },
      { t: "Giữ giá, tập trung chăm sóc khách cũ.", s: "kien_tao" },
      { t: "Tìm điểm khác biệt để không phải đua giá.", s: "dan_duong" },
      { t: "Hoang mang, sợ mất hết khách.", s: "tam_guong" },
    ],
  },
  {
    id: "tv004",
    title: "Ý tưởng khởi nghiệp",
    sit: "Bạn ấp ủ ý tưởng mở quán 2 năm nay. Vốn đã đủ, mặt bằng đẹp vừa xuất hiện.",
    opts: [
      { t: "Cọc mặt bằng ngay, làm rồi tính.", s: "khoi_xuong" },
      { t: "Lên kế hoạch chi tiết 6 tháng rồi mới làm.", s: "kien_tao" },
      { t: "Đi khảo sát 10 quán quanh đó trước.", s: "dan_duong" },
      { t: "Sợ thất bại nên cứ chần chừ mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv005",
    title: "Khách bom hàng",
    sit: "Khách đặt đơn 50 triệu rồi biến mất, hàng đã nhập về. Vốn đang kẹt.",
    opts: [
      { t: "Đăng bán xả ngay để thu hồi vốn.", s: "khoi_xuong" },
      { t: "Tìm khách mới thay thế, cần mẫn chào hàng.", s: "kien_tao" },
      { t: "Rút kinh nghiệm: đơn lớn phải cọc trước.", s: "dan_duong" },
      { t: "Tức và buồn, mất niềm tin vào khách.", s: "tam_guong" },
    ],
  },
  {
    id: "tv006",
    title: "Cãi nhau với đối tác",
    sit: "Đối tác muốn rút vốn giữa chừng vì bất đồng chiến lược. Công ty đang cần tiền.",
    opts: [
      { t: "Mua luôn phần vốn của họ, tự làm tự chịu.", s: "khoi_xuong" },
      { t: "Thương lượng từng điều khoản để giữ họ lại.", s: "kien_tao" },
      { t: "Ngồi lại xem bất đồng nằm ở đâu.", s: "dan_duong" },
      { t: "Buồn vì tình bạn rạn nứt.", s: "tam_guong" },
    ],
  },
  {
    id: "tv007",
    title: "Thương hiệu bị bóc phốt",
    sit: "Một bài bóc phốt quán bạn lên xu hướng, đúng 50%. Khách hủy bàn liên tục.",
    opts: [
      { t: "Livestream xin lỗi và khắc phục ngay tối nay.", s: "khoi_xuong" },
      { t: "Âm thầm sửa sai, để chất lượng tự nói.", s: "kien_tao" },
      { t: "Tìm hiểu ai đứng sau bài viết trước.", s: "dan_duong" },
      { t: "Suy sụp, muốn đóng quán luôn.", s: "tam_guong" },
    ],
  },
  {
    id: "tv008",
    title: "Cơ hội mở chi nhánh",
    sit: "Quán đầu lãi tốt, có người rủ mở chi nhánh 2 ở quận khác. Vốn phải vay thêm.",
    opts: [
      { t: "Mở luôn, thời tới không chờ ai.", s: "khoi_xuong" },
      { t: "Chờ quán đầu ổn định 1 năm nữa.", s: "kien_tao" },
      { t: "Tính kỹ dòng tiền rồi mới quyết.", s: "dan_duong" },
      { t: "Ham mà sợ, hỏi ý kiến khắp nơi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv009",
    title: "Nhân viên gian lận",
    sit: "Bạn phát hiện thu ngân gian tiền 3 tháng nay, số tiền không nhỏ. Họ khóc lóc xin tha.",
    opts: [
      { t: "Cho nghỉ ngay, không có lần hai.", s: "khoi_xuong" },
      { t: "Lập biên bản, trừ lương dần để họ trả.", s: "kien_tao" },
      { t: "Tìm hiểu vì sao họ làm vậy trước.", s: "dan_duong" },
      { t: "Thương mà giận, không nỡ đuổi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv010",
    title: "Khách trả giá rẻ mạt",
    sit: "Khách ép giá xuống dưới cả giá vốn, dọa “không bán thì sang shop khác”.",
    opts: [
      { t: "Từ chối thẳng, bán lỗ thì nghỉ bán.", s: "khoi_xuong" },
      { t: "Giảm chút đỉnh để giữ khách quen.", s: "kien_tao" },
      { t: "Hỏi ngân sách của họ rồi gợi ý món khác.", s: "dan_duong" },
      { t: "Sợ mất khách nên bán dù biết lỗ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv011",
    title: "Tháng ế ẩm",
    sit: "Doanh số tháng này bằng nửa tháng trước. Tiền mặt bằng, lương vẫn phải trả đủ.",
    opts: [
      { t: "Chạy khuyến mãi sốc ngay tuần này.", s: "khoi_xuong" },
      { t: "Cắt giảm chi phí, gồng qua tháng.", s: "kien_tao" },
      { t: "Xem lại vì sao ế: mùa vụ hay do mình.", s: "dan_duong" },
      { t: "Mất ăn mất ngủ vì lo.", s: "tam_guong" },
    ],
  },
  {
    id: "tv012",
    title: "Được mời hợp tác lớn",
    sit: "Thương hiệu lớn mời bạn hợp tác độc quyền, nhưng điều kiện khá gò bó.",
    opts: [
      { t: "Ký luôn, cơ hội lớn không đến hai lần.", s: "khoi_xuong" },
      { t: "Từ chối để giữ tự do làm nghề.", s: "kien_tao" },
      { t: "Đàm phán lại điều khoản rồi quyết.", s: "dan_duong" },
      { t: "Phân vân giữa tiền và tự do.", s: "tam_guong" },
    ],
  },
  {
    id: "tv013",
    title: "Sai sót hợp đồng",
    sit: "Bạn ký nhầm điều khoản bất lợi, đối tác phát hiện và đòi thực hiện đúng chữ.",
    opts: [
      { t: "Nhận sai và thương lượng lại ngay.", s: "khoi_xuong" },
      { t: "Chấp nhận thiệt, coi như học phí.", s: "kien_tao" },
      { t: "Nhờ luật sư xem còn cách nào không.", s: "dan_duong" },
      { t: "Tự trách mình ẩu, buồn mấy ngày.", s: "tam_guong" },
    ],
  },
  {
    id: "tv014",
    title: "Nhân viên mới lười",
    sit: "Nhân viên mới vào 2 tuần mà lười, nhắc thì dạ nhưng không sửa.",
    opts: [
      { t: "Cho nghỉ việc, tuyển người khác.", s: "kien_tao" },
      { t: "Giao việc rõ ràng kèm deadline cụ thể.", s: "dan_duong" },
      { t: "Ngại nói thẳng nên cứ gánh việc thay.", s: "tam_guong" },
      { t: "Cảnh cáo thẳng lần cuối cùng.", s: "khoi_xuong" },
    ],
  },
  {
    id: "tv015",
    title: "Khách VIP phàn nàn",
    sit: "Khách VIP chiếm 30% doanh số dọa bỏ đi vì một lỗi nhỏ của nhân viên.",
    opts: [
      { t: "Đến gặp trực tiếp xin lỗi ngay hôm nay.", s: "khoi_xuong" },
      { t: "Tặng ưu đãi lớn để giữ chân.", s: "kien_tao" },
      { t: "Tìm hiểu xem họ giận lỗi này hay chuyện khác.", s: "dan_duong" },
      { t: "Sợ mất khách đến run tay.", s: "tam_guong" },
    ],
  },
  {
    id: "tv016",
    title: "Tiền nhàn rỗi",
    sit: "Cuối năm dư 500 triệu tiền mặt. Lãi ngân hàng thấp, chứng khoán bấp bênh.",
    opts: [
      { t: "All-in vào ý tưởng mới mình tin.", s: "khoi_xuong" },
      { t: "Gửi tiết kiệm cho chắc ăn.", s: "kien_tao" },
      { t: "Chia ra: một phần an toàn, một phần mạo hiểm.", s: "dan_duong" },
      { t: "Giữ tiền mặt vì sợ mất.", s: "tam_guong" },
    ],
  },
  {
    id: "tv017",
    title: "Bị nhân viên cũ cạnh tranh",
    sit: "Nhân viên cũ mở quán y hệt ngay đối diện, giá rẻ hơn, kéo cả khách quen.",
    opts: [
      { t: "Nâng cấp quán mình vượt trội luôn.", s: "khoi_xuong" },
      { t: "Giữ chất lượng, chăm khách cũ tốt hơn.", s: "kien_tao" },
      { t: "Xem họ hơn mình ở điểm nào để học.", s: "dan_duong" },
      { t: "Buồn và thấy bị phản bội.", s: "tam_guong" },
    ],
  },
  {
    id: "tv018",
    title: "Thuế kiểm tra",
    sit: "Cơ quan thuế báo kiểm tra đột xuất tuần sau. Sổ sách bạn hơi lộn xộn.",
    opts: [
      { t: "Thuê dịch vụ kế toán xử lý gấp ngay.", s: "khoi_xuong" },
      { t: "Thức mấy đêm tự rà soát lại hết.", s: "kien_tao" },
      { t: "Hỏi người có kinh nghiệm xem cần chuẩn bị gì.", s: "dan_duong" },
      { t: "Lo đến mất ngủ dù chưa chắc có gì.", s: "tam_guong" },
    ],
  },
  {
    id: "tv019",
    title: "Mở bán online",
    sit: "Quán offline ổn định, nhiều người khuyên bán thêm online. Bạn mù công nghệ.",
    opts: [
      { t: "Mở gian hàng ngay, vừa làm vừa học.", s: "khoi_xuong" },
      { t: "Thuê người làm, mình lo chất lượng.", s: "kien_tao" },
      { t: "Học thử 1 tháng rồi mới quyết.", s: "dan_duong" },
      { t: "Sợ thay đổi nên cứ chần chừ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv020",
    title: "Đối tác chậm thanh toán",
    sit: "Đối tác nợ 200 triệu quá hạn 2 tháng, gọi thì hứa, gặp thì tránh.",
    opts: [
      { t: "Đến tận nơi đòi cho ra lẽ.", s: "khoi_xuong" },
      { t: "Gửi công văn đòi nợ đúng quy trình.", s: "kien_tao" },
      { t: "Tìm hiểu xem họ khó khăn thật hay chây ì.", s: "dan_duong" },
      { t: "Ngại làm căng nên cứ chờ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv021",
    title: "Tuyển người thân",
    sit: "Người nhà nhờ xin việc cho con, nhưng năng lực chưa đạt. Từ chối thì mất lòng.",
    opts: [
      { t: "Từ chối thẳng, việc là việc.", s: "khoi_xuong" },
      { t: "Nhận vào vị trí phù hợp năng lực.", s: "kien_tao" },
      { t: "Cho thử việc 1 tháng rồi đánh giá.", s: "dan_duong" },
      { t: "Nhận cho yên chuyện dù biết sẽ mệt.", s: "tam_guong" },
    ],
  },
  {
    id: "tv022",
    title: "Giá nguyên liệu tăng",
    sit: "Nguyên liệu chính tăng 40%, tăng giá bán thì sợ mất khách.",
    opts: [
      { t: "Tăng giá luôn, chất lượng không giảm.", s: "khoi_xuong" },
      { t: "Giữ giá, gồng lời ít đi.", s: "kien_tao" },
      { t: "Tìm nhà cung cấp khác tốt hơn.", s: "dan_duong" },
      { t: "Đau đầu không biết làm sao.", s: "tam_guong" },
    ],
  },
  {
    id: "tv023",
    title: "Nhân viên tài năng đòi tăng lương",
    sit: "Người giỏi nhất đòi tăng 50% không thì nghỉ. Quỹ lương đang căng.",
    opts: [
      { t: "Tăng ngay, mất người giỏi là mất hết.", s: "khoi_xuong" },
      { t: "Tăng một phần kèm lộ trình rõ ràng.", s: "kien_tao" },
      { t: "Hỏi xem họ cần tiền hay cần được công nhận.", s: "dan_duong" },
      { t: "Buồn vì thấy mình bạc đãi nhân viên.", s: "tam_guong" },
    ],
  },
  {
    id: "tv024",
    title: "Thất bại đầu tiên",
    sit: "Cửa hàng đầu tiên lỗ 6 tháng liền. Vốn liếng sắp cạn.",
    opts: [
      { t: "Đóng cửa nhanh, giữ vốn làm cái khác.", s: "khoi_xuong" },
      { t: "Gồng thêm 3 tháng xem sao.", s: "kien_tao" },
      { t: "Mổ xẻ xem sai ở đâu rồi quyết.", s: "dan_duong" },
      { t: "Suy sụp, thấy mình thất bại.", s: "tam_guong" },
    ],
  },
  {
    id: "tv025",
    title: "Khách đặt số lượng lớn",
    sit: "Khách đặt gấp 10 lần bình thường, giao trong 1 tuần. Xưởng bạn quá tải.",
    opts: [
      { t: "Nhận luôn, thuê thêm người làm ngày đêm.", s: "khoi_xuong" },
      { t: "Nhận một nửa trong khả năng.", s: "kien_tao" },
      { t: "Xin thêm thời gian rồi nhận hết.", s: "dan_duong" },
      { t: "Sợ làm không nổi nên định từ chối.", s: "tam_guong" },
    ],
  },
  {
    id: "tv026",
    title: "Bị sao chép sản phẩm",
    sit: "Shop khác copy y hệt sản phẩm của bạn, bán rẻ hơn một nửa.",
    opts: [
      { t: "Ra mẫu mới ngay, bỏ xa chúng.", s: "khoi_xuong" },
      { t: "Đăng ký bảo hộ rồi kiện nếu cần.", s: "kien_tao" },
      { t: "Xem họ copy được đến đâu để đối phó.", s: "dan_duong" },
      { t: "Tức tối mà chưa biết làm gì.", s: "tam_guong" },
    ],
  },
  {
    id: "tv027",
    title: "Lên chức quản lý",
    sit: "Bạn được lên quản lý, phải quản cả những người lớn tuổi hơn mình.",
    opts: [
      { t: "Họp team ngay, đặt luật rõ từ đầu.", s: "khoi_xuong" },
      { t: "Làm gương bằng kết quả, dần dần họ nể.", s: "kien_tao" },
      { t: "Tìm hiểu từng người trước rồi mới quản.", s: "dan_duong" },
      { t: "Áp lực, sợ không ai nghe mình.", s: "tam_guong" },
    ],
  },
  {
    id: "tv028",
    title: "Khách hàng say xỉn",
    sit: "Khách say quậy phá trong quán, các bàn khác khó chịu. Họ là khách quen.",
    opts: [
      { t: "Mời họ ra ngoài ngay, quán còn khách khác.", s: "khoi_xuong" },
      { t: "Nhẹ nhàng dỗ dành, gọi xe đưa về.", s: "kien_tao" },
      { t: "Nhờ người đi cùng họ khuyên giúp.", s: "dan_duong" },
      { t: "Khó xử, sợ mất lòng khách quen.", s: "tam_guong" },
    ],
  },
  {
    id: "tv029",
    title: "Đầu tư thua lỗ",
    sit: "Khoản đầu tư 300 triệu bay hơi 40% trong 1 tháng. Cắt lỗ hay gồng?",
    opts: [
      { t: "Cắt lỗ ngay, giữ vốn làm việc khác.", s: "khoi_xuong" },
      { t: "Gồng tiếp, tin vào dài hạn.", s: "kien_tao" },
      { t: "Xem lại vì sao lỗ rồi mới quyết.", s: "dan_duong" },
      { t: "Hoảng loạn, muốn bán hết.", s: "tam_guong" },
    ],
  },
  {
    id: "tv030",
    title: "Được lên báo",
    sit: "Báo lớn muốn phỏng vấn về câu chuyện khởi nghiệp của bạn. Bạn chưa từng lên sóng.",
    opts: [
      { t: "Nhận lời ngay, đây là quảng cáo miễn phí.", s: "khoi_xuong" },
      { t: "Chuẩn bị kỹ từng câu trả lời rồi mới nhận.", s: "kien_tao" },
      { t: "Hỏi rõ góc bài viết thế nào đã.", s: "dan_duong" },
      { t: "Ngại, sợ nói không hay.", s: "tam_guong" },
    ],
  },
  {
    id: "tv031",
    title: "Chia lợi nhuận",
    sit: "Cuối năm lãi lớn, đối tác muốn chia hết, bạn muốn tái đầu tư.",
    opts: [
      { t: "Thuyết phục tái đầu tư, năm sau ăn to.", s: "khoi_xuong" },
      { t: "Chia một nửa, giữ một nửa.", s: "kien_tao" },
      { t: "Đưa số liệu ra bàn cho rõ.", s: "dan_duong" },
      { t: "Nhường đối tác cho êm chuyện.", s: "tam_guong" },
    ],
  },
  {
    id: "tv032",
    title: "Tuyển sai người",
    sit: "Người mới tuyển 1 tháng đã gây gổ với cả team. Hợp đồng thử việc sắp hết.",
    opts: [
      { t: "Không ký tiếp, tiễn luôn.", s: "khoi_xuong" },
      { t: "Gia hạn thử việc kèm điều kiện.", s: "kien_tao" },
      { t: "Nói chuyện riêng xem vấn đề ở đâu.", s: "dan_duong" },
      { t: "Ngại đuổi nên cứ để vậy.", s: "tam_guong" },
    ],
  },
  {
    id: "tv033",
    title: "Khách trả hàng vô lý",
    sit: "Khách dùng sản phẩm 1 tháng rồi đòi trả, viện đủ lý do. Quy định chỉ đổi trong 7 ngày.",
    opts: [
      { t: "Từ chối theo đúng quy định.", s: "khoi_xuong" },
      { t: "Nhận lại cho êm, coi như chi phí.", s: "kien_tao" },
      { t: "Hỏi rõ lý do rồi tìm cách xử lý.", s: "dan_duong" },
      { t: "Sợ bị đánh giá xấu nên nhận dù ấm ức.", s: "tam_guong" },
    ],
  },
  {
    id: "tv034",
    title: "Mở rộng sai thời điểm",
    sit: "Bạn vừa mở thêm chi nhánh thì thị trường đóng băng. Cả 2 nơi đều lỗ.",
    opts: [
      { t: "Đóng bớt một nơi, giữ cái mạnh nhất.", s: "khoi_xuong" },
      { t: "Gồng cả hai, chờ thị trường hồi.", s: "kien_tao" },
      { t: "Tính xem nơi nào có cửa sống cao hơn.", s: "dan_duong" },
      { t: "Hoảng và hối hận vì quyết định vội.", s: "tam_guong" },
    ],
  },
  {
    id: "tv035",
    title: "Nhân viên ốm hàng loạt",
    sit: "Nửa team nghỉ ốm đúng tuần cao điểm. Khách vẫn đông.",
    opts: [
      { t: "Xắn tay vào làm cùng anh em luôn.", s: "khoi_xuong" },
      { t: "Thuê thời vụ gấp để gánh.", s: "kien_tao" },
      { t: "Ưu tiên khách quan trọng trước.", s: "dan_duong" },
      { t: "Căng thẳng, sợ phục vụ không xuể.", s: "tam_guong" },
    ],
  },
  {
    id: "tv036",
    title: "Được đề nghị mua lại",
    sit: "Công ty lớn muốn mua lại thương hiệu của bạn với giá tốt. Bạn gây dựng nó 5 năm.",
    opts: [
      { t: "Bán luôn, cầm tiền làm cái to hơn.", s: "khoi_xuong" },
      { t: "Từ chối — đây là đứa con của mình.", s: "kien_tao" },
      { t: "Nghe điều kiện rồi mới quyết.", s: "dan_duong" },
      { t: "Tiếc mà ham, phân vân mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv037",
    title: "Quảng cáo không hiệu quả",
    sit: "Đốt 50 triệu chạy quảng cáo mà đơn về lẹt đẹt. Agency bảo “cần thêm thời gian”.",
    opts: [
      { t: "Cắt ngay, tự làm cách khác.", s: "khoi_xuong" },
      { t: "Cho thêm 1 tháng với mục tiêu rõ.", s: "kien_tao" },
      { t: "Xem số liệu xem tắc ở đâu.", s: "dan_duong" },
      { t: "Tiếc tiền mà không dám cắt.", s: "tam_guong" },
    ],
  },
  {
    id: "tv038",
    title: "Họp với nhà đầu tư",
    sit: "Ngày mai gặp nhà đầu tư, họ sẽ hỏi rất gắt. Slide của bạn mới xong 70%.",
    opts: [
      { t: "Thức đêm hoàn thiện, mai chiến.", s: "khoi_xuong" },
      { t: "Tập trả lời các câu hỏi khó nhất.", s: "kien_tao" },
      { t: "Tìm hiểu xem họ quan tâm điều gì nhất.", s: "dan_duong" },
      { t: "Lo đến mức không tập trung được.", s: "tam_guong" },
    ],
  },
  {
    id: "tv039",
    title: "Đồng nghiệp đùn việc",
    sit: "Đồng nghiệp hay đùn việc khó sang bạn, sếp thì không biết. Bạn ôm đồm đến kiệt sức.",
    opts: [
      { t: "Nói thẳng với họ ngay.", s: "khoi_xuong" },
      { t: "Ghi lại công việc rõ ràng để sếp thấy.", s: "kien_tao" },
      { t: "Hỏi xem họ quá tải thật hay lười.", s: "dan_duong" },
      { t: "Ôm tiếp vì ngại từ chối.", s: "tam_guong" },
    ],
  },
  {
    id: "tv040",
    title: "Lên giá dịch vụ",
    sit: "Bạn muốn tăng giá 20% vì chi phí leo thang. Sợ khách quen bỏ đi.",
    opts: [
      { t: "Tăng luôn, ai ở lại là khách thật.", s: "khoi_xuong" },
      { t: "Tăng dần từng đợt nhỏ.", s: "kien_tao" },
      { t: "Hỏi ý kiến vài khách thân trước.", s: "dan_duong" },
      { t: "Muốn tăng mà sợ nên thôi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv041",
    title: "Mất khách hàng lớn",
    sit: "Khách chiếm 40% doanh thu chuyển sang đối thủ. Lý do: “bên kia rẻ hơn”.",
    opts: [
      { t: "Tìm ngay 3 khách mới bù vào.", s: "khoi_xuong" },
      { t: "Chăm 60% còn lại tốt gấp đôi.", s: "kien_tao" },
      { t: "Hỏi thật xem họ đi vì giá hay vì khác.", s: "dan_duong" },
      { t: "Suy sụp, thấy công sức đổ sông.", s: "tam_guong" },
    ],
  },
  {
    id: "tv042",
    title: "Ý tưởng bị sếp bác",
    sit: "Bạn trình bày ý tưởng tâm huyết, sếp gạt phắt: “Không khả thi.”",
    opts: [
      { t: "Tranh luận đến cùng để bảo vệ ý tưởng.", s: "khoi_xuong" },
      { t: "Về làm lại chỉn chu hơn rồi trình lại.", s: "kien_tao" },
      { t: "Hỏi sếp thấy không khả thi ở điểm nào.", s: "dan_duong" },
      { t: "Nản, không muốn đề xuất gì nữa.", s: "tam_guong" },
    ],
  },
  {
    id: "tv043",
    title: "Làm thêm giờ liên tục",
    sit: "Cả tháng nay ngày nào bạn cũng về sau 9h tối. Sức khỏe báo động.",
    opts: [
      { t: "Xin nghỉ phép 1 tuần hồi sức ngay.", s: "khoi_xuong" },
      { t: "Cố nốt dự án này rồi nghỉ.", s: "kien_tao" },
      { t: "Xem việc nào bỏ được để giảm tải.", s: "dan_duong" },
      { t: "Mệt mà không dám nghỉ, sợ bị đánh giá.", s: "tam_guong" },
    ],
  },
  {
    id: "tv044",
    title: "Khách hàng nước ngoài",
    sit: "Đối tác nước ngoài sang thăm xưởng ngày mai. Tiếng Anh của bạn chỉ ở mức đọc hiểu.",
    opts: [
      { t: "Tự tin đón tiếp, kém thì dùng phiên dịch.", s: "khoi_xuong" },
      { t: "Chuẩn bị tài liệu song ngữ thật kỹ.", s: "kien_tao" },
      { t: "Tìm hiểu văn hóa của họ để tiếp đón cho phải.", s: "dan_duong" },
      { t: "Lo lắng, sợ mất mặt.", s: "tam_guong" },
    ],
  },
  {
    id: "tv045",
    title: "Sản phẩm lỗi hàng loạt",
    sit: "Lô hàng 1000 chiếc lỗi 30%. Khách đang chờ giao.",
    opts: [
      { t: "Dừng giao, làm lại lô mới ngay.", s: "khoi_xuong" },
      { t: "Lọc hàng lỗi, giao hàng đạt trước.", s: "kien_tao" },
      { t: "Tìm nguyên nhân lỗi trước đã.", s: "dan_duong" },
      { t: "Hoảng, sợ mất uy tín.", s: "tam_guong" },
    ],
  },
  {
    id: "tv046",
    title: "Được mời diễn thuyết",
    sit: "Trường đại học mời bạn chia sẻ kinh nghiệm khởi nghiệp. Bạn chưa nói trước đám đông bao giờ.",
    opts: [
      { t: "Nhận lời ngay, run thì run vẫn nói.", s: "khoi_xuong" },
      { t: "Chuẩn bị slide thật kỹ rồi nhận.", s: "kien_tao" },
      { t: "Hỏi rõ đối tượng nghe là ai đã.", s: "dan_duong" },
      { t: "Từ chối vì sợ nói không hay.", s: "tam_guong" },
    ],
  },
  {
    id: "tv047",
    title: "Vay vốn ngân hàng",
    sit: "Ngân hàng duyệt khoản vay 1 tỷ nhưng lãi suất cao hơn dự kiến.",
    opts: [
      { t: "Vay luôn, cơ hội không chờ.", s: "khoi_xuong" },
      { t: "Không vay, làm nhỏ chắc ăn.", s: "kien_tao" },
      { t: "So sánh 3 ngân hàng rồi quyết.", s: "dan_duong" },
      { t: "Sợ nợ nên chần chừ mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv048",
    title: "Nhân viên cãi khách",
    sit: "Nhân viên cãi tay đôi với khách ngay tại quán. Khách đăng clip lên mạng.",
    opts: [
      { t: "Xin lỗi công khai và xử lý nhân viên ngay.", s: "khoi_xuong" },
      { t: "Gọi cả hai bên ra nói chuyện.", s: "kien_tao" },
      { t: "Xem clip kỹ xem ai đúng ai sai.", s: "dan_duong" },
      { t: "Hoảng vì sợ ảnh hưởng quán.", s: "tam_guong" },
    ],
  },
  {
    id: "tv049",
    title: "Cuối năm thưởng ít",
    sit: "Công ty lãi ít nên thưởng Tết mỏng. Nhân viên xì xào bất mãn.",
    opts: [
      { t: "Họp công khai tình hình cho rõ.", s: "khoi_xuong" },
      { t: "Bù bằng ngày nghỉ và phúc lợi khác.", s: "kien_tao" },
      { t: "Lắng nghe xem anh em cần gì nhất.", s: "dan_duong" },
      { t: "Áy náy, thấy mình làm chủ kém.", s: "tam_guong" },
    ],
  },
  {
    id: "tv050",
    title: "Xu hướng mới",
    sit: "Thị trường rộ xu hướng mới, ai cũng đổ xô theo. Bạn chưa hiểu rõ nó.",
    opts: [
      { t: "Nhảy vào ngay, chậm là mất phần.", s: "khoi_xuong" },
      { t: "Đứng ngoài, làm tốt việc của mình.", s: "kien_tao" },
      { t: "Nghiên cứu kỹ rồi mới quyết.", s: "dan_duong" },
      { t: "Sợ bỏ lỡ mà cũng sợ đu đỉnh.", s: "tam_guong" },
    ],
  },
  {
    id: "tv051",
    title: "Hợp đồng béo bở",
    sit: "Hợp đồng 2 tỷ nhưng yêu cầu “lại quả” 10%. Không chi thì mất.",
    opts: [
      { t: "Từ chối ngay, làm ăn phải sạch.", s: "khoi_xuong" },
      { t: "Tìm cách khác để thắng thầu.", s: "kien_tao" },
      { t: "Cân nhắc rủi ro pháp lý thật kỹ.", s: "dan_duong" },
      { t: "Day dứt giữa tiền và lương tâm.", s: "tam_guong" },
    ],
  },
  {
    id: "tv052",
    title: "Sếp giao việc ngoài khả năng",
    sit: "Sếp giao dự án vượt xa năng lực hiện tại của bạn. Từ chối thì sợ, nhận thì lo.",
    opts: [
      { t: "Nhận luôn, vừa làm vừa học.", s: "khoi_xuong" },
      { t: "Nhận nhưng xin thêm người hỗ trợ.", s: "kien_tao" },
      { t: "Hỏi rõ kỳ vọng rồi mới nhận.", s: "dan_duong" },
      { t: "Nhận vì sợ, đêm về lo không ngủ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv053",
    title: "Khách hàng im lặng",
    sit: "Gửi báo giá 1 tuần khách không trả lời. Gọi thì không nghe máy.",
    opts: [
      { t: "Nhắn thẳng: anh/chị còn quan tâm không?", s: "khoi_xuong" },
      { t: "Gửi thêm thông tin hữu ích, nuôi dần.", s: "kien_tao" },
      { t: "Chờ thêm vài hôm rồi hỏi lại.", s: "dan_duong" },
      { t: "Buồn, nghĩ chắc họ chê rồi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv054",
    title: "Cháy hàng",
    sit: "Sản phẩm bán chạy gấp 5 lần dự kiến, kho hết sạch. Khách đặt vẫn ùn ùn.",
    opts: [
      { t: "Tăng giá ngay vì cầu vượt cung.", s: "khoi_xuong" },
      { t: "Nhận đặt trước, hẹn giao đúng hẹn.", s: "kien_tao" },
      { t: "Tìm nguồn hàng bổ sung gấp.", s: "dan_duong" },
      { t: "Vui mà lo, sợ làm khách thất vọng.", s: "tam_guong" },
    ],
  },
  {
    id: "tv055",
    title: "Bị chơi xấu",
    sit: "Đối thủ tung tin đồn thất thiệt về quán bạn. Khách bắt đầu xì xào.",
    opts: [
      { t: "Lên tiếng đính chính ngay công khai.", s: "khoi_xuong" },
      { t: "Im lặng làm tốt, sự thật tự rõ.", s: "kien_tao" },
      { t: "Thu thập bằng chứng rồi xử lý.", s: "dan_duong" },
      { t: "Tức mà không biết làm sao.", s: "tam_guong" },
    ],
  },
  {
    id: "tv056",
    title: "Nghỉ việc mở riêng",
    sit: "Bạn ấp ủ nghỉ việc mở shop riêng. Lương hiện tại 25 triệu, ổn định.",
    opts: [
      { t: "Nghỉ luôn, an toàn là kẻ thù của giàu.", s: "khoi_xuong" },
      { t: "Làm song song đến khi shop đủ nuôi mình.", s: "kien_tao" },
      { t: "Tính kỹ 6 tháng dự phòng rồi quyết.", s: "dan_duong" },
      { t: "Muốn mà sợ, năm nào cũng hẹn năm sau.", s: "tam_guong" },
    ],
  },
  {
    id: "tv057",
    title: "Team mất đoàn kết",
    sit: "Team bạn chia 2 phe, họp nào cũng cãi. Tiến độ đình trệ.",
    opts: [
      { t: "Họp khẩn, đặt luật: việc ra việc.", s: "khoi_xuong" },
      { t: "Tổ chức team building gắn kết lại.", s: "kien_tao" },
      { t: "Nói riêng từng người tìm gốc rễ.", s: "dan_duong" },
      { t: "Buồn vì team từng thân nhau.", s: "tam_guong" },
    ],
  },
  {
    id: "tv058",
    title: "Khách khen trên mạng",
    sit: "Khách review 5 sao kèm lời khen có cánh. Bài viết được chia sẻ nhiều.",
    opts: [
      { t: "Chia sẻ ngay lên fanpage quán.", s: "khoi_xuong" },
      { t: "Cảm ơn khách và giữ vững chất lượng.", s: "kien_tao" },
      { t: "Hỏi khách điều gì khiến họ hài lòng nhất.", s: "dan_duong" },
      { t: "Vui nhưng lo lần sau không giữ được.", s: "tam_guong" },
    ],
  },
  {
    id: "tv059",
    title: "Tăng ca ngày lễ",
    sit: "Sếp yêu cầu cả team làm xuyên lễ vì đơn gấp. Ai cũng có kế hoạch riêng.",
    opts: [
      { t: "Nhận làm gương, kêu gọi anh em cùng gánh.", s: "khoi_xuong" },
      { t: "Chia ca hợp lý để ai cũng có ngày nghỉ.", s: "kien_tao" },
      { t: "Hỏi sếp có dời được phần nào không.", s: "dan_duong" },
      { t: "Bực mà không dám ý kiến.", s: "tam_guong" },
    ],
  },
  {
    id: "tv060",
    title: "Phát hiện gian lận của sếp",
    sit: "Bạn vô tình thấy sếp khai khống chi phí. Nói ra thì mất việc, im thì day dứt.",
    opts: [
      { t: "Tố cáo theo đúng quy trình.", s: "khoi_xuong" },
      { t: "Im lặng, lo việc của mình.", s: "kien_tao" },
      { t: "Thu thập bằng chứng chắc chắn đã.", s: "dan_duong" },
      { t: "Day dứt mãi không yên.", s: "tam_guong" },
    ],
  },
  {
    id: "tv061",
    title: "Đàm phán lương",
    sit: "Buổi đàm phán lương, HR đưa mức thấp hơn kỳ vọng 20%. Bạn rất thích công việc này.",
    opts: [
      { t: "Đưa ra con số của mình, không nhận thấp.", s: "khoi_xuong" },
      { t: "Chấp nhận, chứng minh rồi tăng sau.", s: "kien_tao" },
      { t: "Hỏi lộ trình tăng lương cụ thể.", s: "dan_duong" },
      { t: "Sợ mất việc nên gật đại.", s: "tam_guong" },
    ],
  },
  {
    id: "tv062",
    title: "Dự án thất bại",
    sit: "Dự án bạn phụ trách lỗ nặng. Sếp gọi lên “nói chuyện”.",
    opts: [
      { t: "Nhận trách nhiệm và đề xuất cách cứu.", s: "khoi_xuong" },
      { t: "Chuẩn bị báo cáo chi tiết nguyên nhân.", s: "kien_tao" },
      { t: "Ngẫm xem sai từ đâu để trình bày.", s: "dan_duong" },
      { t: "Sợ đến mức muốn xin nghỉ luôn.", s: "tam_guong" },
    ],
  },
  {
    id: "tv063",
    title: "Khách hàng thân thiết",
    sit: "Khách 5 năm bỗng ít ghé hẳn. Hỏi thì bảo “dạo này bận”.",
    opts: [
      { t: "Gọi điện hỏi thăm ngay.", s: "khoi_xuong" },
      { t: "Gửi ưu đãi tri ân đặc biệt.", s: "kien_tao" },
      { t: "Tìm hiểu xem họ sang quán khác không.", s: "dan_duong" },
      { t: "Buồn, sợ mình làm gì phật lòng họ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv064",
    title: "Máy móc hỏng",
    sit: "Máy chính của xưởng hỏng đúng mùa cao điểm. Sửa mất 1 tuần.",
    opts: [
      { t: "Thuê máy khác ngay, không để đứt hàng.", s: "khoi_xuong" },
      { t: "Chia việc cho máy còn lại, tăng ca.", s: "kien_tao" },
      { t: "Hỏi thợ xem sửa gấp được không.", s: "dan_duong" },
      { t: "Lo lắng vì sợ trễ đơn.", s: "tam_guong" },
    ],
  },
  {
    id: "tv065",
    title: "Được thưởng lớn",
    sit: "Bạn được thưởng 6 tháng lương vì dự án thành công. Cả team nhìn vào.",
    opts: [
      { t: "Khai tiệc chiêu đãi cả team luôn.", s: "khoi_xuong" },
      { t: "Cất đi, tiếp tục làm việc.", s: "kien_tao" },
      { t: "Chia sẻ một phần với người hỗ trợ mình.", s: "dan_duong" },
      { t: "Vui nhưng ngại vì sợ người ta ganh tị.", s: "tam_guong" },
    ],
  },
  {
    id: "tv066",
    title: "Chuyển đổi số",
    sit: "Công ty bắt dùng phần mềm mới, ai cũng than khó. Bạn cũng mù tịt.",
    opts: [
      { t: "Mày mò dùng luôn, sai đâu sửa đó.", s: "khoi_xuong" },
      { t: "Học từng bước theo tài liệu.", s: "kien_tao" },
      { t: "Hỏi người thạo nhất chỉ cho.", s: "dan_duong" },
      { t: "Than cùng mọi người rồi dùng kiểu cũ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv067",
    title: "Bị cướp công",
    sit: "Đồng nghiệp báo cáo ý tưởng của bạn thành của họ. Sếp khen họ nức nở.",
    opts: [
      { t: "Lên tiếng ngay trong họp.", s: "khoi_xuong" },
      { t: "Gặp riêng sếp trình bày bằng chứng.", s: "kien_tao" },
      { t: "Thu thập bằng chứng rồi mới nói.", s: "dan_duong" },
      { t: "Tức mà im, sợ bị nói nhỏ nhen.", s: "tam_guong" },
    ],
  },
  {
    id: "tv068",
    title: "Mở thêm dịch vụ mới",
    sit: "Khách hay hỏi dịch vụ bạn chưa có. Đầu tư thì tốn kém, không làm thì tiếc.",
    opts: [
      { t: "Triển khai thử ngay 1 tháng.", s: "khoi_xuong" },
      { t: "Từ từ nghiên cứu rồi làm chắc.", s: "kien_tao" },
      { t: "Khảo sát xem bao nhiêu khách thật sự cần.", s: "dan_duong" },
      { t: "Muốn làm mà sợ lỗ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv069",
    title: "Nhân viên xin ứng lương",
    sit: "Nhân viên mới xin ứng 1 tháng lương vì “việc gia đình gấp”. Bạn chưa hiểu họ lắm.",
    opts: [
      { t: "Cho ứng luôn, ai chẳng có lúc khó.", s: "khoi_xuong" },
      { t: "Cho ứng một nửa theo quy định.", s: "kien_tao" },
      { t: "Hỏi rõ chuyện gì rồi quyết.", s: "dan_duong" },
      { t: "Không nỡ từ chối nên cho ứng hết.", s: "tam_guong" },
    ],
  },
  {
    id: "tv070",
    title: "Cuộc họp định mệnh",
    sit: "15 phút nữa họp quyết định số phận dự án của bạn. Tài liệu còn thiếu 1 số liệu.",
    opts: [
      { t: "Vào họp tự tin, thiếu thì bổ sung sau.", s: "khoi_xuong" },
      { t: "Gọi xin dời họp 30 phút để chuẩn bị.", s: "kien_tao" },
      { t: "Nhờ đồng nghiệp tìm giúp số liệu.", s: "dan_duong" },
      { t: "Run đến mức không nghĩ được gì.", s: "tam_guong" },
    ],
  },
  {
    id: "tv071",
    title: "Khách nước ngoài trả giá",
    sit: "Khách Tây trả giá quyết liệt, thấp hơn 40%. Họ bảo “ở nước tôi giá thế này”.",
    opts: [
      { t: "Giữ giá, không bán thì thôi.", s: "khoi_xuong" },
      { t: "Giảm chút đỉnh lấy quan hệ lâu dài.", s: "kien_tao" },
      { t: "Giải thích giá trị để họ hiểu.", s: "dan_duong" },
      { t: "Sợ mất khách nên giảm sâu.", s: "tam_guong" },
    ],
  },
  {
    id: "tv072",
    title: "Bị đánh giá 1 sao",
    sit: "Quán bị đánh giá 1 sao vô lý: “Chưa ăn nhưng thấy đông nên ghét.”",
    opts: [
      { t: "Trả lời công khai, ngắn gọn, đanh thép.", s: "khoi_xuong" },
      { t: "Kệ, một đánh giá không nói lên gì.", s: "kien_tao" },
      { t: "Nhờ khách quen đánh giá thật cân bằng lại.", s: "dan_duong" },
      { t: "Buồn cả ngày vì một người xa lạ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv073",
    title: "Đồng nghiệp nghỉ hết",
    sit: "3 người trong team 5 người nghỉ cùng tháng. Việc đổ lên đầu bạn.",
    opts: [
      { t: "Đề xuất sếp tuyển gấp và tăng lương giữ người.", s: "khoi_xuong" },
      { t: "Gánh việc, chờ tuyển người mới.", s: "kien_tao" },
      { t: "Tìm hiểu vì sao mọi người nghỉ.", s: "dan_duong" },
      { t: "Nản, cũng muốn nghỉ theo.", s: "tam_guong" },
    ],
  },
  {
    id: "tv074",
    title: "Lợi nhuận kỷ lục",
    sit: "Tháng này lãi gấp 3 bình thường. Tiền về đầy tài khoản.",
    opts: [
      { t: "Tái đầu tư hết để bứt phá.", s: "khoi_xuong" },
      { t: "Để dành phòng tháng xấu.", s: "kien_tao" },
      { t: "Chia ra: thưởng team, dự phòng, đầu tư.", s: "dan_duong" },
      { t: "Vui mà lo không giữ được phong độ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv075",
    title: "Sai sót của cấp dưới",
    sit: "Nhân viên làm sai gây thiệt hại 20 triệu. Họ mới vào 1 tháng.",
    opts: [
      { t: "Phê bình thẳng và yêu cầu đền bù.", s: "khoi_xuong" },
      { t: "Bỏ qua lần đầu, đào tạo lại kỹ.", s: "kien_tao" },
      { t: "Xem quy trình có lỗi không, hay lỗi người.", s: "dan_duong" },
      { t: "Giận mà thương, không nỡ phạt.", s: "tam_guong" },
    ],
  },
  {
    id: "tv076",
    title: "Đi công tác xa",
    sit: "Công ty cử đi công tác tỉnh xa 1 tháng. Nhà có con nhỏ.",
    opts: [
      { t: "Đi ngay, cơ hội thăng tiến đây.", s: "khoi_xuong" },
      { t: "Xin ở nhà, gia đình là trên hết.", s: "kien_tao" },
      { t: "Bàn với gia đình rồi quyết.", s: "dan_duong" },
      { t: "Muốn đi mà áy náy với vợ con.", s: "tam_guong" },
    ],
  },
  {
    id: "tv077",
    title: "Khách hàng giới thiệu",
    sit: "Khách quen giới thiệu bạn họ đến, nhưng người này rất khó tính.",
    opts: [
      { t: "Phục vụ như thường, khó mấy cũng chiều.", s: "khoi_xuong" },
      { t: "Cảm ơn khách quen, phục vụ chu đáo hơn.", s: "kien_tao" },
      { t: "Hỏi khách quen về tính người này trước.", s: "dan_duong" },
      { t: "Áp lực vì sợ làm mất mặt người giới thiệu.", s: "tam_guong" },
    ],
  },
  {
    id: "tv078",
    title: "Thay đổi chiến lược",
    sit: "Sếp đột ngột đổi chiến lược, bao công sức team 3 tháng đổ sông.",
    opts: [
      { t: "Triển khai hướng mới ngay, không tiếc.", s: "khoi_xuong" },
      { t: "Xin giữ lại phần nào dùng được.", s: "kien_tao" },
      { t: "Hỏi sếp lý do đổi để hiểu.", s: "dan_duong" },
      { t: "Nản vì công sức mất hết.", s: "tam_guong" },
    ],
  },
  {
    id: "tv079",
    title: "Tiền thưởng Tết",
    sit: "Bạn là chủ, năm nay lãi ít. Thưởng Tết bao nhiêu cho 10 nhân viên?",
    opts: [
      { t: "Thưởng hậu hĩnh, anh em theo mình cả năm.", s: "khoi_xuong" },
      { t: "Thưởng theo đúng quy định đã hứa.", s: "kien_tao" },
      { t: "Họp chia sẻ tình hình rồi cùng quyết.", s: "dan_duong" },
      { t: "Áy náy vì không thưởng nhiều được.", s: "tam_guong" },
    ],
  },
  {
    id: "tv080",
    title: "Bị từ chối hợp tác",
    sit: "Thương hiệu bạn ngưỡng mộ từ chối hợp tác: “Chưa phù hợp.”",
    opts: [
      { t: "Hỏi luôn cần gì để phù hợp.", s: "khoi_xuong" },
      { t: "Về nâng tầm rồi quay lại sau.", s: "kien_tao" },
      { t: "Tìm hiểu xem họ hợp tác với ai.", s: "dan_duong" },
      { t: "Tự ái, thấy mình còn nhỏ bé.", s: "tam_guong" },
    ],
  },
  {
    id: "tv081",
    title: "Khách đặt rồi hủy",
    sit: "Khách đặt tiệc 100 mâm rồi hủy trước 3 ngày. Nguyên liệu đã nhập.",
    opts: [
      { t: "Giữ cọc theo đúng thỏa thuận.", s: "khoi_xuong" },
      { t: "Thương lượng hoàn một phần.", s: "kien_tao" },
      { t: "Tìm khách khác thay thế gấp.", s: "dan_duong" },
      { t: "Buồn vì mất công chuẩn bị.", s: "tam_guong" },
    ],
  },
  {
    id: "tv082",
    title: "Nhân viên giỏi xin nghỉ phép dài",
    sit: "Người giỏi nhất xin nghỉ 1 tháng du lịch đúng mùa cao điểm.",
    opts: [
      { t: "Duyệt luôn, người giỏi cần nạp pin.", s: "khoi_xuong" },
      { t: "Từ chối khéo, qua mùa rồi nghỉ.", s: "kien_tao" },
      { t: "Thương lượng nghỉ ngắn hơn.", s: "dan_duong" },
      { t: "Khó xử, sợ họ nghỉ luôn.", s: "tam_guong" },
    ],
  },
  {
    id: "tv083",
    title: "Giá thuê mặt bằng tăng",
    sit: "Chủ nhà đòi tăng 30% nếu ký tiếp. Quán bạn đã có tiếng ở đây.",
    opts: [
      { t: "Chuyển đi luôn, khách thật sẽ theo.", s: "khoi_xuong" },
      { t: "Chấp nhận tăng để giữ vị trí.", s: "kien_tao" },
      { t: "Đàm phán mức tăng hợp lý hơn.", s: "dan_duong" },
      { t: "Tiếc vị trí mà xót tiền.", s: "tam_guong" },
    ],
  },
  {
    id: "tv084",
    title: "Bị khách quỵt tiền",
    sit: "Khách ăn xong bảo “quên ví” rồi đi luôn không quay lại. Camera ghi rõ mặt.",
    opts: [
      { t: "Đăng clip lên mạng tìm người.", s: "khoi_xuong" },
      { t: "Bỏ qua, coi như xui.", s: "kien_tao" },
      { t: "Báo công an phường xử lý.", s: "dan_duong" },
      { t: "Tức mà không làm gì được.", s: "tam_guong" },
    ],
  },
  {
    id: "tv085",
    title: "Mở bán giờ vàng",
    sit: "Bạn định livestream bán hàng giờ vàng tối nay nhưng chưa chuẩn bị gì.",
    opts: [
      { t: "Live luôn, vừa live vừa xoay.", s: "khoi_xuong" },
      { t: "Dời sang mai để chuẩn bị kỹ.", s: "kien_tao" },
      { t: "Chuẩn bị nhanh những thứ cần nhất rồi live.", s: "dan_duong" },
      { t: "Run nên cứ lần lữa mãi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv086",
    title: "Đồng nghiệp được thăng chức",
    sit: "Người vào sau bạn được thăng chức trước. Bạn làm lâu hơn, việc nhiều hơn.",
    opts: [
      { t: "Hỏi sếp thẳng tiêu chí là gì.", s: "khoi_xuong" },
      { t: "Chúc mừng họ, cố gắng hơn.", s: "kien_tao" },
      { t: "Ngẫm xem mình thiếu điều gì.", s: "dan_duong" },
      { t: "Tủi thân, thấy mình bị bỏ quên.", s: "tam_guong" },
    ],
  },
  {
    id: "tv087",
    title: "Khách hàng khóc",
    sit: "Khách nữ bỗng khóc khi kể chuyện gia đình trong lúc tư vấn. Bạn lúng túng.",
    opts: [
      { t: "An ủi ngay, gác chuyện bán hàng sang bên.", s: "khoi_xuong" },
      { t: "Đưa khăn giấy, im lặng lắng nghe.", s: "kien_tao" },
      { t: "Hỏi xem có thể giúp gì cho họ.", s: "dan_duong" },
      { t: "Bối rối theo, không biết làm gì.", s: "tam_guong" },
    ],
  },
  {
    id: "tv088",
    title: "Thua thầu",
    sit: "Gói thầu theo đuổi 3 tháng rơi vào tay đối thủ. Team rã rời.",
    opts: [
      { t: "Tìm gói khác ngay, không ngồi tiếc.", s: "khoi_xuong" },
      { t: "Tổng kết bài học rồi làm tiếp.", s: "kien_tao" },
      { t: "Tìm hiểu vì sao mình thua.", s: "dan_duong" },
      { t: "Nản cùng cả team.", s: "tam_guong" },
    ],
  },
  {
    id: "tv089",
    title: "Trúng thầu lớn",
    sit: "Bạn trúng gói thầu 5 tỷ, lớn nhất từ trước đến nay. Vừa mừng vừa run.",
    opts: [
      { t: "Ăn mừng rồi bắt tay làm ngay.", s: "khoi_xuong" },
      { t: "Lên kế hoạch triển khai thật chắc.", s: "kien_tao" },
      { t: "Chia nhỏ việc, giao đúng người.", s: "dan_duong" },
      { t: "Vui mà lo không làm nổi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv090",
    title: "Sếp rủ góp vốn",
    sit: "Sếp rủ bạn góp vốn làm ăn riêng ngoài công ty. Lời hứa hẹn hấp dẫn.",
    opts: [
      { t: "Góp luôn, tin sếp.", s: "khoi_xuong" },
      { t: "Từ chối, không lẫn lộn công tư.", s: "kien_tao" },
      { t: "Xem kỹ dự án rồi mới quyết.", s: "dan_duong" },
      { t: "Muốn từ chối mà sợ sếp phật ý.", s: "tam_guong" },
    ],
  },
  {
    id: "tv091",
    title: "Ngày khai trương",
    sit: "Sáng mai khai trương quán mới. Tối nay bạn kiểm tra còn 10 việc chưa xong.",
    opts: [
      { t: "Thức làm hết, mai khai trương hoành tráng.", s: "khoi_xuong" },
      { t: "Ưu tiên việc quan trọng, còn lại mai tính.", s: "kien_tao" },
      { t: "Huy động cả nhà cùng làm cho nhanh.", s: "dan_duong" },
      { t: "Lo đến mức không ngủ được.", s: "tam_guong" },
    ],
  },
  {
    id: "tv092",
    title: "Khách so sánh giá",
    sit: "Khách chìa điện thoại: “Shop kia bán rẻ hơn 100 nghìn.” Bạn biết hàng họ kém hơn.",
    opts: [
      { t: "Nói thẳng: tiền nào của nấy.", s: "khoi_xuong" },
      { t: "Giảm nhẹ để giữ khách.", s: "kien_tao" },
      { t: "Chỉ ra điểm khác biệt của hàng mình.", s: "dan_duong" },
      { t: "Sợ mất khách nên giảm theo.", s: "tam_guong" },
    ],
  },
  {
    id: "tv093",
    title: "Bị sa thải",
    sit: "Công ty cắt giảm, bạn nằm trong danh sách. Sáng mai là ngày cuối.",
    opts: [
      { t: "Rải CV ngay trong tuần này.", s: "khoi_xuong" },
      { t: "Nghỉ ngơi 1 tháng rồi tính.", s: "kien_tao" },
      { t: "Ngẫm xem mình muốn gì tiếp theo.", s: "dan_duong" },
      { t: "Suy sụp, thấy mình vô dụng.", s: "tam_guong" },
    ],
  },
  {
    id: "tv094",
    title: "Lên chức bất ngờ",
    sit: "Sếp nghỉ đột ngột, bạn được đôn lên thay. Team nhìn bạn chờ đợi.",
    opts: [
      { t: "Nhận ngay, chứng minh bằng hành động.", s: "khoi_xuong" },
      { t: "Nhận nhưng xin thời gian làm quen.", s: "kien_tao" },
      { t: "Gặp từng người trong team trước.", s: "dan_duong" },
      { t: "Áp lực, sợ không gánh nổi.", s: "tam_guong" },
    ],
  },
  {
    id: "tv095",
    title: "Khách hàng im hơi",
    sit: "Khách tiềm năng lớn bỗng im lặng sau 2 buổi gặp rất tốt. Bạn đã kỳ vọng nhiều.",
    opts: [
      { t: "Gọi thẳng hỏi cho rõ.", s: "khoi_xuong" },
      { t: "Gửi thêm tài liệu nuôi dần.", s: "kien_tao" },
      { t: "Nhờ người quen hỏi thăm tình hình.", s: "dan_duong" },
      { t: "Buồn, nghĩ chắc họ chọn người khác.", s: "tam_guong" },
    ],
  },
  {
    id: "tv096",
    title: "Cuối năm nhìn lại",
    sit: "Đêm 30 Tết, bạn ngồi tính: năm nay lãi ít hơn năm ngoái. Vợ con đã ngủ.",
    opts: [
      { t: "Lên mục tiêu năm mới thật máu.", s: "khoi_xuong" },
      { t: "Tự nhủ: còn sức khỏe là còn tất cả.", s: "kien_tao" },
      { t: "Ngẫm xem năm nay sai ở đâu.", s: "dan_duong" },
      { t: "Buồn vì thấy mình giậm chân tại chỗ.", s: "tam_guong" },
    ],
  },
  {
    id: "tv097",
    title: "Người quen nhờ vả công việc",
    sit: "Người quen nhờ bạn “ưu tiên” hồ sơ của họ. Hồ sơ đó chưa đạt chuẩn.",
    opts: [
      { t: "Từ chối thẳng, đúng quy trình.", s: "khoi_xuong" },
      { t: "Hướng dẫn họ hoàn thiện hồ sơ.", s: "kien_tao" },
      { t: "Xem thiếu ở đâu rồi tính.", s: "dan_duong" },
      { t: "Nể quá nên gật đại.", s: "tam_guong" },
    ],
  },
  {
    id: "tv098",
    title: "Cạnh tranh không lành mạnh",
    sit: "Đối thủ thuê người đánh giá xấu quán bạn hàng loạt. Điểm tụt thê thảm.",
    opts: [
      { t: "Báo cáo nền tảng và lên tiếng ngay.", s: "khoi_xuong" },
      { t: "Nhờ khách thật đánh giá lại.", s: "kien_tao" },
      { t: "Thu thập bằng chứng chơi xấu của họ.", s: "dan_duong" },
      { t: "Tức tối mà thấy bất lực.", s: "tam_guong" },
    ],
  },
  {
    id: "tv099",
    title: "Quyết định nghỉ hưu sớm",
    sit: "Bạn 45 tuổi, tài chính đủ sống. Nghỉ để hưởng thụ hay làm tiếp vì đam mê?",
    opts: [
      { t: "Nghỉ luôn, đời ngắn lắm.", s: "khoi_xuong" },
      { t: "Làm tiếp, nghỉ thì buồn chân tay.", s: "kien_tao" },
      { t: "Giảm dần việc, chuyển giao cho người khác.", s: "dan_duong" },
      { t: "Muốn nghỉ mà sợ hụt hẫng.", s: "tam_guong" },
    ],
  },
  {
    id: "tv100",
    title: "Di sản để lại",
    sit: "Bạn tự hỏi: 20 năm nữa người ta nhớ đến mình vì điều gì?",
    opts: [
      { t: "Người dám làm những việc không ai dám.", s: "khoi_xuong" },
      { t: "Người làm việc tử tế đến cùng.", s: "kien_tao" },
      { t: "Người dẫn dắt được nhiều người.", s: "dan_duong" },
      { t: "Người sống tình cảm với mọi người.", s: "tam_guong" },
    ],
  },
];
